// Generated by CoffeeScript 2.7.0
(function() {
  var KycUpdateCall, Request;

  Request = require('../../../../request');

  /*
    This method is used to update the call status with the latest info
    received from the main system. It also updates the transaction
    associated with this verification call.
  */
  KycUpdateCall = class KycUpdateCall extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'json');
    }

    getTransactionType() {
      return 'kyc_update_call';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'kyc',
        path: 'api/v1/update_authentication'
      };
    }

    getTrxData() {
      return this.params;
    }

  };

  module.exports = KycUpdateCall;

}).call(this);
