// Generated by CoffeeScript 2.7.0
(function() {
  var KycMakeCall, Request;

  Request = require('../../../../request');

  /*
    This method is used to make a call or send an SMS to a given phone number.
    This method is used to complement the verification process.
    The system will make a call and dictate the verification code to be typed in the website.
  */
  KycMakeCall = class KycMakeCall extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'json');
    }

    getTransactionType() {
      return 'kyc_make_call';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'kyc',
        path: 'api/v1/create_authentication'
      };
    }

    getTrxData() {
      return this.params;
    }

  };

  module.exports = KycMakeCall;

}).call(this);
