// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, GlobalPayout, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  /*
    Global Payout is a transaction type based on Open Banking APIs, used for initiating bank payments
  */
  GlobalPayout = class GlobalPayout extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.GLOBAL_PAYOUT;
    }

  };

  module.exports = GlobalPayout;

}).call(this);
