// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, RussianMobilePayout, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  RussianMobilePayout = class RussianMobilePayout extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.RUSSIAN_MOBILE_PAYOUT;
    }

  };

  module.exports = RussianMobilePayout;

}).call(this);
