// Generated by CoffeeScript 2.7.0
(function() {
  var Builders, Form, Xml, _;

  _ = require('underscore');

  Xml = require('./xml');

  Form = require('./form');

  Builders = (function() {
    class Builders {
      constructor(builder) {
        switch (builder) {
          case this.XML:
            this.context = new Xml();
            break;
          case this.FORM:
            this.context = new Form();
            break;
          default:
            this.context = null;
        }
      }

      getBuilder(structure) {
        if (this.context === null) {
          return '';
        }
        return this.context.getConverter(structure);
      }

    };

    // XML Builder Identifier
    Builders.prototype.XML = 'xml';

    // JSON Builder Identifier
    Builders.prototype.JSON = 'json';

    // FORM Builder Identifier
    Builders.prototype.FORM = 'form';

    Builders.prototype.context = '';

    return Builders;

  }).call(this);

  module.exports = Builders;

}).call(this);
