// Generated by CoffeeScript 2.7.0
(function() {
  var Form, _;

  _ = require('underscore');

  Form = class Form {
    //  Convert Object to URL-encoded query string structure
    objToQueryString(structure) {
      return (new URLSearchParams(structure)).toString();
    }

    // Return object converter
    buildStructure(structure) {
      return this.objToQueryString(structure);
    }

  };

  module.exports = Form;

}).call(this);
