// Generated by CoffeeScript 2.7.0
(function() {
  var Json;

  Json = class Json {
    /*
       Convert Object to JSON structure
    */
    objToJSON(structure) {
      return JSON.stringify(structure);
    }

    /*
       Return object converter
    */
    buildStructure(structure) {
      return this.objToJSON(structure);
    }

  };

  module.exports = Json;

}).call(this);
