// Generated by CoffeeScript 2.7.0
(function() {
  var Xml, _, js2xml;

  _ = require('underscore');

  js2xml = require('js2xmlparser');

  Xml = class Xml {
    /*
       Convert Object to XML structure
    */
    objToXml(structure) {
      var rootNode;
      if (_.isEmpty(structure)) {
        return '<?xml version=\'1.0\'?>';
      }
      rootNode = _.first(_.keys(structure));
      return js2xml.parse(rootNode, structure[rootNode]);
    }

    /*
       Return object converter
    */
    buildStructure(structure) {
      return this.objToXml(structure);
    }

  };

  module.exports = Xml;

}).call(this);
