// Generated by CoffeeScript 2.7.0
(function() {
  var Base, Currency, Promise, Request, Validator, _;

  Request = require('../request');

  Currency = require('../helpers/currency');

  _ = require('underscore');

  Promise = require('bluebird');

  Validator = require('./validator');

  Base = class Base extends Request {
    constructor(params, configuration) {
      super('xml', configuration);
      this.params = params;
      this.currency = new Currency();
    }

    setData(params) {
      this.params = params;
      return this;
    }

    getData() {
      if (typeof this.getTransactionType === "function" ? this.getTransactionType() : void 0) {
        return _.extend({}, this.params, {
          transaction_type: this.getTransactionType()
        });
      } else {
        return this.params;
      }
    }

    getArguments() {
      return {
        trx: this.getTrxData(),
        url: this.getUrl()
      };
    }

  };

  module.exports = Base;

}).call(this);
