// Generated by CoffeeScript 2.7.0
(function() {
  var Base, FraudReport;

  Base = require('../../../base');

  FraudReport = class FraudReport extends Base {
    constructor(params) {
      super(params);
    }

    getTransactionType() {
      return 'fraud_report_request';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'fraud_reports'
      };
    }

    getTrxData() {
      return {
        'fraud_report_request': this.params
      };
    }

  };

  module.exports = FraudReport;

}).call(this);
