// Generated by CoffeeScript 2.5.1
(function() {
  var Base, FraudReport;

  Base = require('../../../base');

  FraudReport = class FraudReport extends Base {
    constructor(params) {
      super(params);
      this.requiredFieldsOr = ['arn', 'original_transaction_unique_id'];
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'fraud_reports'
      };
    }

    getTrxData() {
      return {
        'fraud_report_request': this.params
      };
    }

  };

  module.exports = FraudReport;

}).call(this);
