// Generated by CoffeeScript 2.7.0
(function() {

  /*
    This call is used to return all rates for Tier.
  */
  var Rates, Request, util;

  Request = require('../../../request');

  util = require('util');

  Rates = (function() {
    var FX_RATES;

    class Rates extends Request {
      // FX Rates constructor with GET HTTP Request
      constructor(params, configuration) {
        super(params, configuration, 'get');
        this.populateIdentifier();
      }

      // FX Rates transaction type that defines the JSON Schema
      getTransactionType() {
        return 'fx_rates';
      }

      // Rates endpoint
      getUrl() {
        return {
          app: 'gate',
          path: util.format(FX_RATES, this.tierId)
        };
      }

      // Populate Tier ID used in the endpoint
      populateIdentifier() {
        this.tierId = '';
        if (this.params instanceof Object && this.params.hasOwnProperty('tier_id')) {
          return this.tierId = this.params.tier_id;
        }
      }

    };

    FX_RATES = 'v1/fx/tiers/%s/rates';

    return Rates;

  }).call(this);

  module.exports = Rates;

}).call(this);
