// Generated by CoffeeScript 2.7.0
(function() {

  /*
    This call is used to return information about selected Rate for merchant.
  */
  var Rate, Request, util;

  Request = require('../../../request');

  util = require('util');

  Rate = (function() {
    var FX_RATE;

    class Rate extends Request {
      // FX Rate constructor with GET HTTP Request
      constructor(params, configuration) {
        super(params, configuration, 'get');
        this.populateIdentifiers();
      }

      // FX Rate transaction type that defines the JSON Schema
      getTransactionType() {
        return 'fx_rate';
      }

      // Rate endpoint
      getUrl() {
        return {
          app: 'gate',
          path: util.format(FX_RATE, this.tierId, this.identifier)
        };
      }

      // Populate identifiers used in the endpoint
      populateIdentifiers() {
        this.identifier = '';
        this.tierId = '';
        if (this.params instanceof Object && this.params.hasOwnProperty('id')) {
          this.identifier = this.params.id;
        }
        if (this.params instanceof Object && this.params.hasOwnProperty('tier_id')) {
          return this.tierId = this.params.tier_id;
        }
      }

    };

    FX_RATE = 'v1/fx/tiers/%s/rates/%s';

    return Rate;

  }).call(this);

  module.exports = Rate;

}).call(this);
