// Generated by CoffeeScript 2.7.0
(function() {

  /*
    This call is used to return information about selected Rate by currency pair.
  */
  var Request, SearchRate, _, util;

  Request = require('../../../request');

  util = require('util');

  _ = require('underscore');

  SearchRate = (function() {
    var FX_SEARCH_RATE;

    class SearchRate extends Request {
      // FX Search Rate constructor with JSON HTTP POST Request
      constructor(params, configuration) {
        super(params, configuration, 'json');
        this.populateIdentifiers();
      }

      // FX Search Rate transaction type that defines the JSON Schema
      getTransactionType() {
        return 'fx_search_rate';
      }

      // FX Search Rate endpoint
      getUrl() {
        return {
          app: 'gate',
          path: util.format(FX_SEARCH_RATE, this.tierId)
        };
      }

      getTrxData() {
        var params;
        params = _.clone(this.params);
        delete params.tier_id;
        return params;
      }

      // Populate tierId used in the endpoint
      populateIdentifiers() {
        this.tierId = '';
        if (this.params instanceof Object && this.params.hasOwnProperty('tier_id')) {
          return this.tierId = this.params.tier_id;
        }
      }

    };

    FX_SEARCH_RATE = 'v1/fx/tiers/%s/rates/search';

    return SearchRate;

  }).call(this);

  module.exports = SearchRate;

}).call(this);
