// Generated by CoffeeScript 2.7.0
(function() {

  /*
    Returns all Tiers that are related to your account
  */
  var Request, Tiers;

  Request = require('../../../request');

  Tiers = (function() {
    class Tiers extends Request {
      // Tiers constructor with HTTP GET method
      constructor(params, configuration) {
        super(params, configuration, 'get');
      }

      // Tiers type that indicates the used JSON schema
      getTransactionType() {
        return 'fx_tiers';
      }

      // Tiers endpoint
      getUrl() {
        return {
          app: 'gate',
          path: this.FX_TIERS
        };
      }

    };

    Tiers.prototype.FX_TIERS = 'v1/fx/tiers';

    return Tiers;

  }).call(this);

  module.exports = Tiers;

}).call(this);
