// Generated by CoffeeScript 2.7.0
(function() {

  /*
    This call is used to return information about selected Tier for your merchant.
  */
  var Request, Tier;

  Request = require('../../../request');

  Tier = (function() {
    var FX_TIER;

    class Tier extends Request {
      // FX Tier constructor with GET HTTP Request
      constructor(params, configuration) {
        super(params, configuration, 'get');
        this.populateIdentifier();
      }

      // FX Tier transaction type that defines the JSON Schema
      getTransactionType() {
        return 'fx_tier';
      }

      // Tier endpoint
      getUrl() {
        return {
          app: 'gate',
          path: `${FX_TIER}/${this.identifier}`
        };
      }

      // Populate Tier ID used in the endpoint
      populateIdentifier() {
        this.identifier = '';
        if (this.params instanceof Object && this.params.hasOwnProperty('id')) {
          return this.identifier = this.params.id;
        }
      }

    };

    FX_TIER = 'v1/fx/tiers';

    return Tier;

  }).call(this);

  module.exports = Tier;

}).call(this);
