// Generated by CoffeeScript 2.7.0
(function() {
  var CreateConsumer, Request, TransactionTypes;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  CreateConsumer = (function() {
    class CreateConsumer extends Request {
      getTransactionType() {
        return TransactionTypes.CREATE_CONSUMER;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.CREATE_CONSUMER_URL
        };
      }

      getTrxData() {
        return {
          'create_consumer_request': this.params
        };
      }

    };

    CreateConsumer.prototype.CREATE_CONSUMER_URL = 'v1/create_consumer';

    return CreateConsumer;

  }).call(this);

  module.exports = CreateConsumer;

}).call(this);
