// Generated by CoffeeScript 2.7.0
(function() {
  var DisableConsumer, Request, TransactionTypes;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  DisableConsumer = (function() {
    class DisableConsumer extends Request {
      getTransactionType() {
        return TransactionTypes.DISABLE_CONSUMER;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.DISABLE_CONSUMER_URL
        };
      }

      getTrxData() {
        return {
          'disable_consumer_request': this.params
        };
      }

    };

    DisableConsumer.prototype.DISABLE_CONSUMER_URL = 'v1/disable_consumer';

    return DisableConsumer;

  }).call(this);

  module.exports = DisableConsumer;

}).call(this);
