// Generated by CoffeeScript 2.7.0
(function() {
  var EnableConsumer, Request, TransactionTypes;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  EnableConsumer = (function() {
    class EnableConsumer extends Request {
      getTransactionType() {
        return TransactionTypes.ENABLE_CONSUMER;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.ENABLE_CONSUMER_URL
        };
      }

      getTrxData() {
        return {
          'enable_consumer_request': this.params
        };
      }

    };

    EnableConsumer.prototype.ENABLE_CONSUMER_URL = 'v1/enable_consumer';

    return EnableConsumer;

  }).call(this);

  module.exports = EnableConsumer;

}).call(this);
