// Generated by CoffeeScript 2.7.0
(function() {
  var GetCards, Request, TransactionTypes;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  GetCards = (function() {
    class GetCards extends Request {
      getTransactionType() {
        return TransactionTypes.GET_CONSUMER_CARDS;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.GET_CONSUMER_CARDS_URL
        };
      }

      getTrxData() {
        return {
          'get_consumer_cards_request': this.params
        };
      }

    };

    GetCards.prototype.GET_CONSUMER_CARDS_URL = 'v1/get_consumer_cards';

    return GetCards;

  }).call(this);

  module.exports = GetCards;

}).call(this);
