// Generated by CoffeeScript 2.7.0
(function() {
  var Request, RetrieveConsumer, TransactionTypes;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  RetrieveConsumer = (function() {
    class RetrieveConsumer extends Request {
      getTransactionType() {
        return TransactionTypes.RETRIEVE_CONSUMER;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.RETRIEVE_CONSUMER_URL
        };
      }

      getTrxData() {
        return {
          'retrieve_consumer_request': this.params
        };
      }

    };

    RetrieveConsumer.prototype.RETRIEVE_CONSUMER_URL = 'v1/retrieve_consumer';

    return RetrieveConsumer;

  }).call(this);

  module.exports = RetrieveConsumer;

}).call(this);
