// Generated by CoffeeScript 2.7.0
(function() {
  var Request, TransactionTypes, UpdateConsumer;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  UpdateConsumer = (function() {
    class UpdateConsumer extends Request {
      getTransactionType() {
        return TransactionTypes.UPDATE_CONSUMER;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.UPDATE_CONSUMER_URL
        };
      }

      getTrxData() {
        return {
          'update_consumer_request': this.params
        };
      }

    };

    UpdateConsumer.prototype.UPDATE_CONSUMER_URL = 'v1/update_consumer';

    return UpdateConsumer;

  }).call(this);

  module.exports = UpdateConsumer;

}).call(this);
