// Generated by CoffeeScript 2.7.0
(function() {
  var Alipay, FinancialBase, NumberValidator, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  NumberValidator = require('../../../helpers/validators/number_validator');

  Alipay = class Alipay extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.ALIPAY;
    }

  };

  module.exports = Alipay;

}).call(this);
