// Generated by CoffeeScript 2.5.1
(function() {
  var Alipay, FinancialBase, NumberValidator, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  NumberValidator = require('../../../helpers/validators/number_validator');

  Alipay = class Alipay extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.ALIPAY;
    }

    constructor(params) {
      super(params);
      this.requiredFields = _.union(this.requiredFields, ['usage', 'remote_ip', 'return_success_url', 'return_failure_url']);
      this.fieldsValues['currency'] = ['CNY'];
      this.fieldsValues['amount'] = new NumberValidator(10);
    }

  };

  module.exports = Alipay;

}).call(this);
