// Generated by CoffeeScript 2.7.0
(function() {
  var BancoDoBrasil, FinancialBase, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  BancoDoBrasil = class BancoDoBrasil extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.BANCO_DO_BRASIL;
    }

  };

  module.exports = BancoDoBrasil;

}).call(this);
