// Generated by CoffeeScript 2.7.0
(function() {
  var Bradesco, FinancialBase, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Bradesco = class Bradesco extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.BRADESCO;
    }

  };

  module.exports = Bradesco;

}).call(this);
