// Generated by CoffeeScript 2.7.0
(function() {
  var Davivienda, FinancialBase, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Davivienda = class Davivienda extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.DAVIVIENDA;
    }

  };

  module.exports = Davivienda;

}).call(this);
