// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Ideal, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Ideal = class Ideal extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.IDEAL;
    }

  };

  module.exports = Ideal;

}).call(this);
