// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Itau, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Itau = class Itau extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.ITAU;
    }

  };

  module.exports = Itau;

}).call(this);
