// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Multibanco, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Multibanco = class Multibanco extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.MULTIBANCO;
    }

  };

  module.exports = Multibanco;

}).call(this);
