// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, MyBank, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  MyBank = class MyBank extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.MY_BANK;
    }

  };

  module.exports = MyBank;

}).call(this);
