// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, P24, TransactionTypes;

  AlternativeBase = require('../alternative/alternative_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  P24 = class P24 extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.P24;
    }

  };

  module.exports = P24;

}).call(this);
