// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Payu, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Payu = class Payu extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.PAYU;
    }

  };

  module.exports = Payu;

}).call(this);
