// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, PostFinance, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  PostFinance = class PostFinance extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.POST_FINANCE;
    }

  };

  module.exports = PostFinance;

}).call(this);
