// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Pse, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Pse = class Pse extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.PSE;
    }

  };

  module.exports = Pse;

}).call(this);
