// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Santander, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Santander = class Santander extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.SANTANDER;
    }

  };

  module.exports = Santander;

}).call(this);
