// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, TransactionTypes, Upi;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Upi = class Upi extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.UPI;
    }

  };

  module.exports = Upi;

}).call(this);
