// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, TransactionTypes, Webpay;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Webpay = class Webpay extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.WEBPAY;
    }

  };

  module.exports = Webpay;

}).call(this);
