// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, NumberValidator, TransactionTypes, Wechat, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  NumberValidator = require('../../../helpers/validators/number_validator');

  Wechat = class Wechat extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.WECHAT;
    }

  };

  module.exports = Wechat;

}).call(this);
