// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, NumberValidator, TransactionTypes, Wechat, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  NumberValidator = require('../../../helpers/validators/number_validator');

  Wechat = class Wechat extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.WECHAT;
    }

    constructor(params, configuration) {
      super(params, configuration);
      this.requiredFields = _.union(this.requiredFields, ['usage', 'return_success_url', 'return_success_url', 'billing_address.country']);
      this.fieldsValues['amount'] = new NumberValidator(0, 999999);
    }

  };

  module.exports = Wechat;

}).call(this);
