// Generated by CoffeeScript 2.7.0
(function() {
  var Payers, Request, TransactionTypes;

  Request = require('../../../../request');

  TransactionTypes = require('../../../../helpers/transaction/types');

  Payers = (function() {
    class Payers extends Request {
      constructor(params, configuration) {
        super(params, configuration, 'get');
      }

      getTransactionType() {
        return TransactionTypes.TRANSFER_TO_PAYERS;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.TRANSFER_TO_PAYERS_URL
        };
      }

    };

    Payers.prototype.TRANSFER_TO_PAYERS_URL = 'transfer_to_payers/payers';

    return Payers;

  }).call(this);

  module.exports = Payers;

}).call(this);
