// Generated by CoffeeScript 2.7.0
(function() {
  var CardBase, InitRecurringSale3d, TransactionTypes;

  CardBase = require('../card_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  InitRecurringSale3d = class InitRecurringSale3d extends CardBase {
    getTransactionType() {
      return TransactionTypes.INIT_RECURRING_SALE_3D;
    }

    constructor(params) {
      super(params);
    }

  };

  module.exports = InitRecurringSale3d;

}).call(this);
