// Generated by CoffeeScript 2.7.0
(function() {
  var CardBase, InitRecurringSale3d, TransactionTypes, TravelData, _;

  CardBase = require('../card_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  TravelData = require('../../../../helpers/travel_data/travel_data');

  InitRecurringSale3d = class InitRecurringSale3d extends CardBase {
    getTransactionType() {
      return TransactionTypes.INIT_RECURRING_SALE_3D;
    }

    getTrxData() {
      var travelData;
      travelData = new TravelData(this.params);
      travelData.parseTravelData();
      return super.getTrxData();
    }

  };

  module.exports = InitRecurringSale3d;

}).call(this);
