// Generated by CoffeeScript 2.7.0
(function() {
  var CardBase, InitRecurringSale, TransactionTypes;

  CardBase = require('../card_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  InitRecurringSale = class InitRecurringSale extends CardBase {
    getTransactionType() {
      return TransactionTypes.INIT_RECURRING_SALE;
    }

  };

  module.exports = InitRecurringSale;

}).call(this);
