// Generated by CoffeeScript 2.5.1
(function() {
  var FinancialBase, RecurringSale, TransactionTypes, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  RecurringSale = class RecurringSale extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.RECURRING_SALE;
    }

    constructor(params) {
      super(params);
      this.requiredFields = _.union(this.requiredFields, ['reference_id']);
    }

  };

  module.exports = RecurringSale;

}).call(this);
