// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, RecurringSale, TransactionTypes, TravelData, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  TravelData = require('../../../../helpers/travel_data/travel_data');

  RecurringSale = class RecurringSale extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.RECURRING_SALE;
    }

    constructor(params) {
      super(params);
    }

    getTrxData() {
      var travelData;
      travelData = new TravelData(this.params);
      travelData.parseTravelData();
      return super.getTrxData();
    }

  };

  module.exports = RecurringSale;

}).call(this);
