// Generated by CoffeeScript 2.7.0
(function() {
  var JsonUtils, _;

  _ = require('underscore');

  JsonUtils = class JsonUtils {
    static isValidObjectChain(object, chain) {
      var i, len, objectTmp, properties, property;
      if (!_.isObject(object) || _.isEmpty(chain)) {
        return false;
      }
      properties = chain.split('.');
      objectTmp = object;
      for (i = 0, len = properties.length; i < len; i++) {
        property = properties[i];
        if (!objectTmp[property] && !objectTmp.hasOwnProperty(property)) {
          return false;
        }
        objectTmp = objectTmp[property];
      }
      return true;
    }

  };

  module.exports = JsonUtils;

}).call(this);
