// Generated by CoffeeScript 2.7.0
(function() {
  var Base, Reconcile, config;

  Base = require('../../base');

  config = require('config');

  Reconcile = class Reconcile extends Base {
    constructor(params) {
      super(params);
    }

    getTransactionType() {
      return 'reconcile';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'reconcile',
        token: config.customer.token
      };
    }

    getTrxData() {
      return {
        'reconcile': this.params
      };
    }

  };

  module.exports = Reconcile;

}).call(this);
