// Generated by CoffeeScript 2.5.1
(function() {
  var I18n, _;

  _ = require('underscore');

  I18n = (function() {
    class I18n {
      getLocales() {
        var key, ref, results, value;
        ref = this.constructor;
        results = [];
        for (key in ref) {
          value = ref[key];
          results.push(key.toLowerCase());
        }
        return results;
      }

      isValidLocale(locale) {
        return _.indexOf(this.getLocales(), locale.toLowerCase()) !== -1;
      }

    };

    /*
      Arabic locale and language
    */
    I18n.AR = 'Arabic';

    I18n.BG = 'Bulgarian';

    I18n.DE = 'German';

    I18n.EN = 'English';

    I18n.ES = 'Spanish';

    I18n.FR = 'French';

    I18n.HI = 'Hindu';

    I18n.JA = 'Japanese';

    I18n.IS = 'Icelandic';

    I18n.IT = 'Italian';

    I18n.NL = 'Dutch';

    I18n.PT = 'Portuguese';

    I18n.PL = 'Polish';

    I18n.RU = 'Russian';

    I18n.TR = 'Turkish';

    I18n.ZH = 'Chinese (Mandarin)';

    return I18n;

  }).call(this);

  module.exports = I18n;

}).call(this);
