// Generated by CoffeeScript 2.7.0
(function() {
  var I18n, _;

  _ = require('underscore');

  I18n = (function() {
    class I18n {
      getLocales() {
        var key, ref, results, value;
        ref = this.constructor;
        results = [];
        for (key in ref) {
          value = ref[key];
          results.push(key.toLowerCase());
        }
        return results;
      }

      isValidLocale(locale) {
        return _.indexOf(this.getLocales(), locale.toLowerCase()) !== -1;
      }

    };

    /*
      English locale and language settings (this is the default)
    */
    I18n.EN = 'English';

    /*
      Italian locale and language settings
    */
    I18n.IT = 'Italian';

    /*
      Spanish locale and language settings
    */
    I18n.ES = 'Spanish';

    /*
      French locale and language settings
    */
    I18n.FR = 'French';

    /*
      German locale and language
    */
    I18n.DE = 'German';

    /*
      Polish locale and language
    */
    I18n.PL = 'Polish';

    /*
      Japanese locale and language
    */
    I18n.JA = 'Japanese';

    /*
      Mandarin Chinese locale and language
    */
    I18n.ZH = 'Chinese (Mandarin)';

    /*
      Arabic locale and language
    */
    I18n.AR = 'Arabic';

    /*
      Portuguese locale and language
    */
    I18n.PT = 'Portuguese';

    /*
      Turkish locale and language
    */
    I18n.TR = 'Turkish';

    /*
      Russian locale and language
    */
    I18n.RU = 'Russian';

    /*
      Hindu locale and language
    */
    I18n.HI = 'Hindu';

    /*
      Bulgarian locale and language
    */
    I18n.BG = 'Bulgarian';

    /*
      Dutch locale and language
    */
    I18n.NL = 'Dutch';

    /*
      Icelandic locale and language
    */
    I18n.IS = 'Icelandic';

    /*
      Indonesian locale and language
    */
    I18n.ID = 'Indonesian';

    /*
      Malay locale and language
    */
    I18n.MS = 'Malay';

    /*
      Thai locale and language
    */
    I18n.TH = 'Thai';

    /*
      Czech locale and language
    */
    I18n.CS = 'Czech';

    /*
      Croatian locale and language
    */
    I18n.HR = 'Croatian';

    /*
      Slovenian locale and language
    */
    I18n.SL = 'Slovenian';

    /*
      Finnish locale and language
    */
    I18n.FI = 'Finnish';

    /*
      Norwegian locale and language
    */
    I18n.NO = 'Norwegian';

    /*
      Danish locale and language
    */
    I18n.DA = 'Danish';

    /*
      Swedish locale and language
    */
    I18n.SV = 'Swedish';

    return I18n;

  }).call(this);

  module.exports = I18n;

}).call(this);
