// Generated by CoffeeScript 2.7.0
(function() {
  var SmartRouter;

  SmartRouter = class SmartRouter {
    getSmartRouterUrlParams() {
      return {
        app: 'smart_router',
        path: 'transactions'
      };
    }

  };

  module.exports = SmartRouter;

}).call(this);
