// Generated by CoffeeScript 2.7.0
(function() {
  var Methods, _;

  _ = require('underscore');

  Methods = (function() {
    class Methods {
      getMethods() {
        var key, ref, results, value;
        ref = this.constructor;
        results = [];
        for (key in ref) {
          value = ref[key];
          results.push(value);
        }
        return results;
      }

      isValidMethod(method) {
        return _.indexOf(this.getMethods(), method) !== -1;
      }

    };

    /*
      e-payment standard

      PPRO transaction
    */
    Methods.EPS = 'eps';

    /*
      iDEAL

      PPRO transaction
    */
    Methods.IDEAL = 'ideal';

    /*
      Przelewy24

      PPRO transaction
    */
    Methods.PRZELEWY24 = 'przelewy24';

    /*
      SafetyPay

      PPRO transaction
    */
    Methods.SAFETY_PAY = 'safetypay';

    /*
      TrustPay

      PPRO transaction
    */
    Methods.TRUST_PAY = 'trustpay';

    /*
      Mr.Cash

      PPRO transaction
    */
    Methods.BCMC = 'bcmc';

    /*
      MyBank

      PPRO transaction
    */
    Methods.MYBANK = 'mybank';

    return Methods;

  }).call(this);

  module.exports = Methods;

}).call(this);
