// Generated by CoffeeScript 2.5.1
(function() {
  var Cancel, FinancialBase, TransactionTypes;

  FinancialBase = require('./financial_base');

  TransactionTypes = require('../../helpers/transaction/types');

  Cancel = class Cancel extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.VOID;
    }

    constructor(params) {
      super(params);
      this.requiredFields = ['transaction_id', 'reference_id'];
      this.fieldsValues = {};
    }

  };

  module.exports = Cancel;

}).call(this);
