// Generated by CoffeeScript 2.7.0
(function() {
  var Capture, FinancialBase, TransactionTypes, _;

  FinancialBase = require('./financial_base');

  TransactionTypes = require('../../helpers/transaction/types');

  _ = require('underscore');

  Capture = class Capture extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.CAPTURE;
    }

  };

  module.exports = Capture;

}).call(this);
