// Generated by CoffeeScript 2.5.1
(function() {
  var Capture, FinancialBase, TransactionTypes, _;

  FinancialBase = require('./financial_base');

  TransactionTypes = require('../../helpers/transaction/types');

  _ = require('underscore');

  Capture = class Capture extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.CAPTURE;
    }

    constructor(params) {
      super(params);
      this.requiredFields = _.union(this.requiredFields, ['reference_id']);
    }

  };

  module.exports = Capture;

}).call(this);
