// Generated by CoffeeScript 2.7.0
(function() {
  var ColorDepthHelper, FinancialBase, JsonUtils, Request, _;

  Request = require('../../request');

  _ = require('underscore');

  ColorDepthHelper = require('../../helpers/color_depth');

  JsonUtils = require('../../utils/json_utils');

  FinancialBase = class FinancialBase extends Request {
    constructor(params, configuration) {
      super(params, configuration);
      this.formatThreedsV2ColorDepth();
    }

    // Financial transactions endpoint
    getUrl() {
      if (this.params.use_smart_router || this.configuration.getCustomerForceSmartRouter()) {
        return {
          app: 'smart_router',
          path: 'transactions'
        };
      }
      return {
        app: 'gate',
        path: 'process',
        token: this.configuration.getCustomerToken()
      };
    }

    getTrxData() {
      if (this.params.use_smart_router) {
        // Remove use_smart_router from parameters sent to the gateway
        delete this.params.use_smart_router;
      }
      this.formatAmount();
      this.formatManagedRecurringAmount();
      return {
        'payment_transaction': _.extend(this.params, {
          'transaction_type': this.getTransactionType()
        })
      };
    }

    getData() {
      return _.extend({}, this.params, {
        transaction_type: this.getTransactionType()
      });
    }

    // Format the Amount into minor units
    formatAmount() {
      // convert amount to minor units
      if (this.params.amount && this.params.currency) {
        return this.params.amount = this.currency.convertToMinorUnits(this.params.amount, this.params.currency);
      }
    }

    // Format the Managed Recurring Amount into minor units
    formatManagedRecurringAmount() {
      if (this.params.managed_recurring && this.params.currency) {
        if (this.params.managed_recurring.amount) {
          this.params.managed_recurring.amount = this.currency.convertToMinorUnits(this.params.managed_recurring.amount, this.params.currency);
        }
        if (this.params.managed_recurring.max_amount) {
          return this.params.managed_recurring.max_amount = this.currency.convertToMinorUnits(this.params.managed_recurring.max_amount, this.params.currency);
        }
      }
    }

    // Format Color Depth with correct value
    formatThreedsV2ColorDepth() {
      if (JsonUtils.isValidObjectChain(this.params, 'threeds_v2_params.browser.color_depth')) {
        return this.params.threeds_v2_params.browser.color_depth = (new ColorDepthHelper()).handleColorDepth(this.params.threeds_v2_params.browser.color_depth).toString();
      }
    }

  };

  module.exports = FinancialBase;

}).call(this);
