// Generated by CoffeeScript 2.7.0
(function() {
  var AmountValidator, Base, FinancialBase, StringValidator, _, config;

  Base = require('../base');

  _ = require('underscore');

  config = require('config');

  AmountValidator = require('../../helpers/validators/amount_validator');

  StringValidator = require('../../helpers/validators/string_validator');

  FinancialBase = class FinancialBase extends Base {
    constructor(params) {
      super(params);
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'process',
        token: config.customer.token
      };
    }

    getTrxData() {
      // convert amount to minor units
      if (this.params.amount && this.params.currency) {
        this.params.amount = this.currency.convertToMinorUnits(this.params.amount, this.params.currency);
      }
      if (this.params.managed_recurring && this.params.currency) {
        if (this.params.managed_recurring.amount) {
          this.params.managed_recurring.amount = this.currency.convertToMinorUnits(this.params.managed_recurring.amount, this.params.currency);
        }
        if (this.params.managed_recurring.max_amount) {
          this.params.managed_recurring.max_amount = this.currency.convertToMinorUnits(this.params.managed_recurring.max_amount, this.params.currency);
        }
      }
      return {
        'payment_transaction': _.extend(this.params, {
          'transaction_type': this.getTransactionType()
        })
      };
    }

  };

  module.exports = FinancialBase;

}).call(this);
