// Generated by CoffeeScript 2.7.0
(function() {
  var Base, ColorDepth, FinancialBase, JsonUtils, SmartRouter, _, config;

  Base = require('../base');

  _ = require('underscore');

  config = require('config');

  ColorDepth = require('../../helpers/color_depth');

  JsonUtils = require('../../utils/json_utils');

  SmartRouter = require('../../helpers/smart_router');

  FinancialBase = class FinancialBase extends Base {
    constructor(params) {
      super(params);
      this.smartRouterParams = (new SmartRouter()).getSmartRouterUrlParams();
      if (JsonUtils.isValidObjectChain(params, 'threeds_v2_params.browser.color_depth')) {
        this.params.threeds_v2_params.browser.color_depth = (new ColorDepth()).handleColorDepth(params.threeds_v2_params.browser.color_depth).toString();
      }
    }

    getUrl() {
      if (this.params.use_smart_router || this.getForceSmartRouter()) {
        return this.smartRouterParams;
      }
      return {
        app: 'gate',
        path: 'process',
        token: config.customer.token
      };
    }

    getTrxData() {
      // convert amount to minor units
      if (this.params.amount && this.params.currency) {
        this.params.amount = this.currency.convertToMinorUnits(this.params.amount, this.params.currency);
      }
      if (this.params.managed_recurring && this.params.currency) {
        if (this.params.managed_recurring.amount) {
          this.params.managed_recurring.amount = this.currency.convertToMinorUnits(this.params.managed_recurring.amount, this.params.currency);
        }
        if (this.params.managed_recurring.max_amount) {
          this.params.managed_recurring.max_amount = this.currency.convertToMinorUnits(this.params.managed_recurring.max_amount, this.params.currency);
        }
      }
      return {
        'payment_transaction': _.extend(this.params, {
          'transaction_type': this.getTransactionType()
        })
      };
    }

  };

  module.exports = FinancialBase;

}).call(this);
