// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Refund, TransactionTypes, _;

  FinancialBase = require('./financial_base');

  TransactionTypes = require('../../helpers/transaction/types');

  _ = require('underscore');

  Refund = class Refund extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.REFUND;
    }

    constructor(params, configuration) {
      super(params, configuration);
    }

  };

  module.exports = Refund;

}).call(this);
