// Generated by CoffeeScript 2.5.1
(function() {
  var FinancialBase, Refund, TransactionTypes, _;

  FinancialBase = require('./financial_base');

  TransactionTypes = require('../../helpers/transaction/types');

  _ = require('underscore');

  Refund = class Refund extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.REFUND;
    }

    constructor(params) {
      super(params);
      this.requiredFields = _.union(this.requiredFields, ['reference_id']);
    }

  };

  module.exports = Refund;

}).call(this);
