// Generated by CoffeeScript 2.7.0
(function() {
  var KycUploadDocument, Request;

  Request = require('../../../../request');

  /*
    Used to verify documents provided by the customer.
  */
  KycUploadDocument = class KycUploadDocument extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'json');
    }

    getTransactionType() {
      return 'kyc_upload_document';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'kyc',
        path: 'api/v1/upload_document'
      };
    }

    getTrxData() {
      return this.params;
    }

  };

  module.exports = KycUploadDocument;

}).call(this);
