// Generated by CoffeeScript 2.7.0
(function() {
  var KycDownloadDocument, Request;

  Request = require('../../../../request');

  /*
    Uploaded documents will be stored by legal provisions and they can be requested for review.
    Just post a JSON body with the identity document id of the given document and
    a response with the filename and the base64 encoded content of that file would be returned.
  */
  KycDownloadDocument = class KycDownloadDocument extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'json');
    }

    getTransactionType() {
      return 'kyc_download_document';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'kyc',
        path: 'api/v1/download_document'
      };
    }

    getTrxData() {
      return this.params;
    }

  };

  module.exports = KycDownloadDocument;

}).call(this);
