// Generated by CoffeeScript 2.7.0
(function() {
  var Request, Retrieval;

  Request = require('../../../../request');

  Retrieval = class Retrieval extends Request {
    getTransactionType() {
      return 'retrieval_request_request';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'retrieval_requests'
      };
    }

    getTrxData() {
      return {
        'retrieval_request_request': this.params
      };
    }

  };

  module.exports = Retrieval;

}).call(this);
