// Generated by CoffeeScript 2.5.1
(function() {
  var Base, FraudReportByDate;

  Base = require('../../../base');

  FraudReportByDate = class FraudReportByDate extends Base {
    constructor(params) {
      super(params);
      this.requiredFields = ['start_date'];
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'retrieval_requests/by_date'
      };
    }

    getTrxData() {
      return {
        'retrieval_request_request': this.params
      };
    }

  };

  module.exports = FraudReportByDate;

}).call(this);
