// Generated by CoffeeScript 2.7.0
(function() {
  var Base, FraudReportByDate;

  Base = require('../../../base');

  FraudReportByDate = class FraudReportByDate extends Base {
    constructor(params, configuration) {
      super(params, configuration);
    }

    getTransactionType() {
      return 'retrieval_by_date_request_request';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'retrieval_requests/by_date'
      };
    }

    getTrxData() {
      return {
        'retrieval_request_request': this.params
      };
    }

  };

  module.exports = FraudReportByDate;

}).call(this);
