// Generated by CoffeeScript 2.7.0
(function() {
  var Base, Retrieval;

  Base = require('../../../base');

  Retrieval = class Retrieval extends Base {
    getTransactionType() {
      return 'retrieval_request_request';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'retrieval_requests'
      };
    }

    getTrxData() {
      return {
        'retrieval_request_request': this.params
      };
    }

  };

  module.exports = Retrieval;

}).call(this);
