// Generated by CoffeeScript 2.7.0
(function() {
  var FraudReportByDate, Request;

  Request = require('../../../../request');

  FraudReportByDate = class FraudReportByDate extends Request {
    getTransactionType() {
      return 'retrieval_by_date_request_request';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'retrieval_requests/by_date'
      };
    }

    getTrxData() {
      return {
        'retrieval_request_request': this.params
      };
    }

  };

  module.exports = FraudReportByDate;

}).call(this);
