// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, OnlineBankingPayin, TransactionTypes, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  OnlineBankingPayin = class OnlineBankingPayin extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.ONLINE_BANKING_PAYIN;
    }

  };

  module.exports = OnlineBankingPayin;

}).call(this);
