// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, OnlineBankingPayout, TransactionTypes, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  OnlineBankingPayout = class OnlineBankingPayout extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.ONLINE_BANKING_PAYOUT;
    }

  };

  module.exports = OnlineBankingPayout;

}).call(this);
