// Generated by CoffeeScript 2.7.0
(function() {
  var ProcessedTransactions, Request;

  Request = require('../../../request');

  ProcessedTransactions = class ProcessedTransactions extends Request {
    getTransactionType() {
      return 'processed_transactions';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'processed_transactions'
      };
    }

    getTrxData() {
      return {
        'processed_transaction_request': this.params
      };
    }

  };

  module.exports = ProcessedTransactions;

}).call(this);
