// Generated by CoffeeScript 2.7.0
(function() {
  var ProcessedTransactionsByDate, Request;

  Request = require('../../../request');

  ProcessedTransactionsByDate = class ProcessedTransactionsByDate extends Request {
    getTransactionType() {
      return 'processed_transactions_by_date';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'processed_transactions/by_date'
      };
    }

    getTrxData() {
      return {
        'processed_transaction_request': this.params
      };
    }

  };

  module.exports = ProcessedTransactionsByDate;

}).call(this);
