// Generated by CoffeeScript 2.7.0
(function() {
  var ProcessedTransactionsByPostDate, Request;

  Request = require('../../../request');

  ProcessedTransactionsByPostDate = class ProcessedTransactionsByPostDate extends Request {
    getTransactionType() {
      return 'processed_transactions_by_post_date';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'processed_transactions/by_post_date'
      };
    }

    getTrxData() {
      return {
        'processed_transaction_request': this.params
      };
    }

  };

  module.exports = ProcessedTransactionsByPostDate;

}).call(this);
