// Generated by CoffeeScript 2.7.0
(function() {
  var Fetch, Request;

  Request = require('../../../request');

  /*
    Fetch the applicable installments for a given amount, currency and card brand.
  */
  Fetch = class Fetch extends Request {
    // Fetch Installments uses JSON builder
    constructor(params, configuration) {
      super(params, configuration, 'json');
    }

    // Fetch Installments API endpoint
    getUrl() {
      return {
        app: 'gate',
        path: 'v1/installments'
      };
    }

    // Fetch Installments gateway data
    getTrxData() {
      return this.params;
    }

    // Fetch Installments JSON schema
    getTransactionType() {
      return 'installments_fetch';
    }

  };

  module.exports = Fetch;

}).call(this);
