// Generated by CoffeeScript 2.7.0
(function() {
  var Request, ShowDetails, util;

  Request = require('../../../request');

  util = require('util');

  /*
    Retrieves details about a specific installment based on its ID.
  */
  ShowDetails = class ShowDetails extends Request {
    // Show Details Installments uses JSON builder
    constructor(params, configuration) {
      super(params, configuration, 'get');
      this.populateIdentifiers();
    }

    // Show Details Installments API endpoint
    getUrl() {
      return {
        app: 'gate',
        path: util.format('v1/installments/%s', this.installmentId)
      };
    }

    // Show Details Installments JSON schema
    getTransactionType() {
      return 'installments_show_details';
    }

    // Populate identifier used in the endpoint
    populateIdentifiers() {
      this.installmentId = '';
      if (this.params instanceof Object && this.params.hasOwnProperty('installment_id')) {
        return this.installmentId = this.params.installment_id;
      }
    }

  };

  module.exports = ShowDetails;

}).call(this);
