// Generated by CoffeeScript 2.5.1
(function() {
  var Base, ChargebackByDate;

  Base = require('../../../base');

  ChargebackByDate = class ChargebackByDate extends Base {
    constructor(params) {
      super(params);
      this.requiredFields = ['start_date'];
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'chargebacks/by_date'
      };
    }

    getTrxData() {
      return {
        'chargeback_request': this.params
      };
    }

  };

  module.exports = ChargebackByDate;

}).call(this);
