// Generated by CoffeeScript 2.7.0
(function() {
  var Base, Chargeback;

  Base = require('../../../base');

  Chargeback = class Chargeback extends Base {
    getTransactionType() {
      return 'chargeback_request';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'chargebacks'
      };
    }

    getTrxData() {
      return {
        'chargeback_request': this.params
      };
    }

  };

  module.exports = Chargeback;

}).call(this);
