// Generated by CoffeeScript 2.5.1
(function() {
  var Base, Chargeback;

  Base = require('../../../base');

  Chargeback = class Chargeback extends Base {
    constructor(params) {
      super(params);
      this.requiredFieldsOr = ['arn', 'original_transaction_unique_id'];
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'chargebacks'
      };
    }

    getTrxData() {
      return {
        'chargeback_request': this.params
      };
    }

  };

  module.exports = Chargeback;

}).call(this);
