// Generated by CoffeeScript 2.7.0
(function() {
  var Argencard, CardBase, TransactionTypes, _;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Argencard = class Argencard extends CardBase {
    getTransactionType() {
      return TransactionTypes.ARGENCARD;
    }

  };

  module.exports = Argencard;

}).call(this);
