// Generated by CoffeeScript 2.7.0
(function() {
  var Argencard, FinancialBase, TransactionTypes;

  TransactionTypes = require('../../../helpers/transaction/types');

  FinancialBase = require('../financial_base');

  Argencard = class Argencard extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.ARGENCARD;
    }

  };

  module.exports = Argencard;

}).call(this);
