// Generated by CoffeeScript 2.7.0
(function() {
  var Aura, CardBase, TransactionTypes, _;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Aura = class Aura extends CardBase {
    getTransactionType() {
      return TransactionTypes.AURA;
    }

  };

  module.exports = Aura;

}).call(this);
