// Generated by CoffeeScript 2.7.0
(function() {
  var Aura, FinancialBase, TransactionTypes;

  TransactionTypes = require('../../../helpers/transaction/types');

  FinancialBase = require('../financial_base');

  Aura = class Aura extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.AURA;
    }

  };

  module.exports = Aura;

}).call(this);
