// Generated by CoffeeScript 2.7.0
(function() {
  var Authorize3d, CardBase, TransactionTypes;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Authorize3d = class Authorize3d extends CardBase {
    getTransactionType() {
      return TransactionTypes.AUTHORIZE_3D;
    }

    constructor(params) {
      super(params);
    }

  };

  module.exports = Authorize3d;

}).call(this);
