// Generated by CoffeeScript 2.7.0
(function() {
  var Authorize3d, CardBase, TransactionTypes, TravelData, _;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  TravelData = require('../../../helpers/travel_data/travel_data');

  Authorize3d = class Authorize3d extends CardBase {
    getTransactionType() {
      return TransactionTypes.AUTHORIZE_3D;
    }

    getTrxData() {
      var travelData;
      travelData = new TravelData(this.params);
      travelData.parseTravelData();
      return super.getTrxData();
    }

  };

  module.exports = Authorize3d;

}).call(this);
