// Generated by CoffeeScript 2.7.0
(function() {
  var Authorize, CardBase, TransactionTypes, TravelData, _;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  TravelData = require('../../../helpers/travel_data/travel_data');

  Authorize = class Authorize extends CardBase {
    getTransactionType() {
      return TransactionTypes.AUTHORIZE;
    }

    isValid() {
      var valid;
      valid = super.isValid();
      if (this.params.recurring_type === 'subsequent' && _.isEmpty(this.params.reference_id)) {
        this.validator.addError({
          type: 'required',
          property: 'reference_id',
          message: 'Field reference_id has invalid value. Field reference_id is required'
        });
        return false;
      }
      return valid;
    }

    getTrxData() {
      var travelData;
      travelData = new TravelData(this.params);
      travelData.parseTravelData();
      return super.getTrxData();
    }

  };

  module.exports = Authorize;

}).call(this);
