// Generated by CoffeeScript 2.7.0
(function() {
  var Bancontact, CardBase, TransactionTypes, _;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Bancontact = class Bancontact extends CardBase {
    getTransactionType() {
      return TransactionTypes.BANCONTACT;
    }

  };

  module.exports = Bancontact;

}).call(this);
