// Generated by CoffeeScript 2.7.0
(function() {
  var Bancontact, FinancialBase, TransactionTypes;

  TransactionTypes = require('../../../helpers/transaction/types');

  FinancialBase = require('../financial_base');

  Bancontact = class Bancontact extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.BANCONTACT;
    }

  };

  module.exports = Bancontact;

}).call(this);
