// Generated by CoffeeScript 2.7.0
(function() {
  var Cabal, CardBase, TransactionTypes, _;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Cabal = class Cabal extends CardBase {
    getTransactionType() {
      return TransactionTypes.CABAL;
    }

  };

  module.exports = Cabal;

}).call(this);
