// Generated by CoffeeScript 2.7.0
(function() {
  var Cabal, FinancialBase, TransactionTypes;

  TransactionTypes = require('../../../helpers/transaction/types');

  FinancialBase = require('../financial_base');

  Cabal = class Cabal extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.CABAL;
    }

  };

  module.exports = Cabal;

}).call(this);
