// Generated by CoffeeScript 2.5.1
(function() {
  var CardBase, CreditCardValidator, FinancialBase, _;

  FinancialBase = require('../financial_base');

  _ = require('underscore');

  CreditCardValidator = require('../../../helpers/validators/credit_card_validator');

  CardBase = class CardBase extends FinancialBase {
    constructor(params) {
      var creditCardValidator;
      super(params);
      creditCardValidator = new CreditCardValidator();
      this.requiredFields = _.union(this.requiredFields, creditCardValidator.getCCRequiredFields());
      this.fieldsValues = _.extend(this.fieldsValues, creditCardValidator.getCCFieldValueFormatValidators());
    }

    set3DRequiredFields() {
      return this.requiredFieldsGroups = {
        'asynchronous': ['notification_url', 'return_success_url', 'return_failure_url'],
        'synchronous': ['mpi_params.eci']
      };
    }

  };

  module.exports = CardBase;

}).call(this);
