// Generated by CoffeeScript 2.7.0
(function() {
  var CardBase, FinancialBase, _;

  FinancialBase = require('../financial_base');

  _ = require('underscore');

  CardBase = class CardBase extends FinancialBase {
    constructor(params, configuration) {
      super(params, configuration);
    }

    isValid() {
      var valid;
      valid = super.isValid();
      if (!_.isEmpty(this.params.token) && this.params.remember_card === true) {
        this.validator.addError({
          type: 'oneOf',
          property: 'remember_card token',
          message: 'Request depends on specific rules. ' + 'Only one of the following parameters can exists in the request: token or remember_card'
        });
        false;
      }
      return valid;
    }

  };

  module.exports = CardBase;

}).call(this);
