// Generated by CoffeeScript 2.7.0
(function() {
  var Cencosud, FinancialBase, TransactionTypes;

  TransactionTypes = require('../../../helpers/transaction/types');

  FinancialBase = require('../financial_base');

  Cencosud = class Cencosud extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.CENCOSUD;
    }

  };

  module.exports = Cencosud;

}).call(this);
