// Generated by CoffeeScript 2.7.0
(function() {
  var CardBase, Cencosud, TransactionTypes, _;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Cencosud = class Cencosud extends CardBase {
    getTransactionType() {
      return TransactionTypes.CENCOSUD;
    }

  };

  module.exports = Cencosud;

}).call(this);
