// Generated by CoffeeScript 2.5.1
(function() {
  var Credit, FinancialBase, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  _ = require('underscore');

  TransactionTypes = require('../../../helpers/transaction/types');

  Credit = class Credit extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.CREDIT;
    }

    constructor(params) {
      super(params);
      this.requiredFields = _.union(this.requiredFields, ['reference_id']);
    }

  };

  module.exports = Credit;

}).call(this);
