// Generated by CoffeeScript 2.7.0
(function() {
  var Elo, FinancialBase, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Elo = class Elo extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.ELO;
    }

  };

  module.exports = Elo;

}).call(this);
