// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Naranja, TransactionTypes;

  TransactionTypes = require('../../../helpers/transaction/types');

  FinancialBase = require('../financial_base');

  Naranja = class Naranja extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.NARANJA;
    }

  };

  module.exports = Naranja;

}).call(this);
