// Generated by CoffeeScript 2.7.0
(function() {
  var CardBase, Naranja, TransactionTypes, _;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Naranja = class Naranja extends CardBase {
    getTransactionType() {
      return TransactionTypes.NARANJA;
    }

  };

  module.exports = Naranja;

}).call(this);
