// Generated by CoffeeScript 2.7.0
(function() {
  var CardBase, Nativa, TransactionTypes, _;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Nativa = class Nativa extends CardBase {
    getTransactionType() {
      return TransactionTypes.NATIVA;
    }

  };

  module.exports = Nativa;

}).call(this);
