// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Nativa, TransactionTypes;

  TransactionTypes = require('../../../helpers/transaction/types');

  FinancialBase = require('../financial_base');

  Nativa = class Nativa extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.NATIVA;
    }

  };

  module.exports = Nativa;

}).call(this);
