// Generated by CoffeeScript 2.7.0
(function() {
  var CardBase, Sale3d, TransactionTypes, TravelData, _;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  TravelData = require('../../../helpers/travel_data/travel_data');

  Sale3d = class Sale3d extends CardBase {
    getTransactionType() {
      return TransactionTypes.SALE_3D;
    }

    getTrxData() {
      var travelData;
      travelData = new TravelData(this.params);
      travelData.parseTravelData();
      return super.getTrxData();
    }

  };

  module.exports = Sale3d;

}).call(this);
