// Generated by CoffeeScript 2.5.1
(function() {
  var CardBase, Sale, TransactionTypes;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Sale = class Sale extends CardBase {
    getTransactionType() {
      return TransactionTypes.SALE;
    }

  };

  module.exports = Sale;

}).call(this);
