// Generated by CoffeeScript 2.7.0
(function() {
  var CardBase, Sale3d, TransactionTypes;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Sale3d = class Sale3d extends CardBase {
    getTransactionType() {
      return TransactionTypes.SALE_3D;
    }

    constructor(params) {
      super(params);
    }

  };

  module.exports = Sale3d;

}).call(this);
