// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, TarjetaShopping, TransactionTypes;

  TransactionTypes = require('../../../helpers/transaction/types');

  FinancialBase = require('../financial_base');

  TarjetaShopping = class TarjetaShopping extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.TARJETA_SHOPPING;
    }

  };

  module.exports = TarjetaShopping;

}).call(this);
