// Generated by CoffeeScript 2.7.0
(function() {
  var CardBase, TarjetaShopping, TransactionTypes, _;

  CardBase = require('./card_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  TarjetaShopping = class TarjetaShopping extends CardBase {
    getTransactionType() {
      return TransactionTypes.TARJETA_SHOPPING;
    }

  };

  module.exports = TarjetaShopping;

}).call(this);
