// Generated by CoffeeScript 2.5.1
(function() {
  var AccountVerification, Base, CreditCardValidator, TransactionTypes, _, config;

  Base = require('../base');

  TransactionTypes = require('../../helpers/transaction/types');

  _ = require('underscore');

  config = require('config');

  CreditCardValidator = require('../../helpers/validators/credit_card_validator');

  AccountVerification = class AccountVerification extends Base {
    getTransactionType() {
      return TransactionTypes.ACCOUNT_VERIFICATION;
    }

    constructor(params) {
      var creditCardValidator;
      super(params);
      creditCardValidator = new CreditCardValidator();
      this.requiredFields = _.union(['transaction_id', 'billing_address.address1', 'billing_address.zip_code', 'billing_address.city'], creditCardValidator.getCCRequiredFields());
      this.fieldsValues = creditCardValidator.getCCFieldValueFormatValidators();
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'process',
        token: config.customer.token
      };
    }

    getTrxData() {
      return {
        'payment_transaction': _.extend(this.params, {
          'transaction_type': this.getTransactionType()
        })
      };
    }

  };

  module.exports = AccountVerification;

}).call(this);
