// Generated by CoffeeScript 2.7.0
(function() {
  var Blacklist, Request;

  Request = require('../../request');

  Blacklist = class Blacklist extends Request {
    getTransactionType() {
      return 'blacklist_request';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'blacklists'
      };
    }

    getTrxData() {
      return {
        "blacklist_request": this.params
      };
    }

  };

  module.exports = Blacklist;

}).call(this);
