// Generated by CoffeeScript 2.7.0
(function() {
  var Base, Blacklist;

  Base = require('../base');

  Blacklist = class Blacklist extends Base {
    constructor(params) {
      super(params);
    }

    getTransactionType() {
      return 'blacklist_request';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'blacklists'
      };
    }

    getTrxData() {
      return {
        "blacklist_request": this.params
      };
    }

  };

  module.exports = Blacklist;

}).call(this);
