// Generated by CoffeeScript 2.5.1
(function() {
  var Base, Blacklist;

  Base = require('../base');

  Blacklist = class Blacklist extends Base {
    constructor(params) {
      super(params);
      this.requiredFields = ['card_number'];
    }

    getUrl() {
      return {
        app: 'gate',
        path: 'blacklists'
      };
    }

    getTrxData() {
      return {
        'blacklist_request': this.params
      };
    }

  };

  module.exports = Blacklist;

}).call(this);
