// Generated by CoffeeScript 2.5.1
(function() {
  var FinancialBase, IDebitPayin, StringValidator, TransactionTypes, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  StringValidator = require('../../../../helpers/validators/string_validator');

  IDebitPayin = class IDebitPayin extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.IDEBIT_PAYIN;
    }

    constructor(params) {
      super(params);
      this.requiredFields = _.union(this.requiredFields, ['return_url', 'customer_account_id', 'customer_email', 'billing_address.country']);
      this.fieldsValues['transaction_id'] = new StringValidator(1, 30);
      this.fieldsValues['billing_address.country'] = ['CA'];
      this.fieldsValues['currency'] = ['CAD', 'USD', 'EUR', 'GBP', 'AUD'];
    }

  };

  module.exports = IDebitPayin;

}).call(this);
