// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, IDebitPayin, TransactionTypes, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  IDebitPayin = class IDebitPayin extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.IDEBIT_PAYIN;
    }

  };

  module.exports = IDebitPayin;

}).call(this);
