// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, IDebitPayout, TransactionTypes, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  IDebitPayout = class IDebitPayout extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.IDEBIT_PAYOUT;
    }

  };

  module.exports = IDebitPayout;

}).call(this);
