// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, IDebitPayout, StringValidator, TransactionTypes, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  StringValidator = require('../../../../helpers/validators/string_validator');

  IDebitPayout = class IDebitPayout extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.IDEBIT_PAYOUT;
    }

    constructor(params) {
      super(params);
    }

  };

  module.exports = IDebitPayout;

}).call(this);
