// Generated by CoffeeScript 2.5.1
(function() {
  var FinancialBase, IDebitPayout, StringValidator, TransactionTypes, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  StringValidator = require('../../../../helpers/validators/string_validator');

  IDebitPayout = class IDebitPayout extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.IDEBIT_PAYOUT;
    }

    constructor(params) {
      super(params);
      this.requiredFields = _.union(this.requiredFields, ['reference_id']);
      this.fieldsValues['transaction_id'] = new StringValidator(1, 30);
    }

  };

  module.exports = IDebitPayout;

}).call(this);
