// Generated by CoffeeScript 2.7.0
(function() {
  var config, genesis, params;

  process.env.NODE_CONFIG_DIR = process.env.NODE_CONFIG_DIR ? process.env.NODE_CONFIG_DIR : require('path').join(__dirname, '..', 'config');

  config = require("config");

  params = {
    version: '3.0.2'
  };

  config.util.setModuleDefaults('module', params);

  genesis = {
    currency: require('./genesis/helpers/currency'),
    notification: require('./genesis/notification'),
    request: require('./genesis/request'),
    transaction: require('./genesis/transaction')
  };

  module.exports = genesis;

}).call(this);
