// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, IncrementalAuthorize, TransactionTypes, _;

  FinancialBase = require('./../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  IncrementalAuthorize = class IncrementalAuthorize extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.INCREMENTAL_AUTHORIZE;
    }

  };

  module.exports = IncrementalAuthorize;

}).call(this);
