// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, PartialReversal, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  PartialReversal = class PartialReversal extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.PARTIAL_REVERSAL;
    }

  };

  module.exports = PartialReversal;

}).call(this);
