// Generated by CoffeeScript 2.7.0
(function() {
  // JSON Response Parser
  var Json;

  Json = class Json {
    // JSON parser initialization
    constructor() {
      this.object = {};
      this.parseRootNode = false;
    }

    // Parsed Object to JSON
    getObject() {
      return this.object;
    }

    // Remove root element from the parsed structure
    skipRootNode() {
      return this.parseRootNode = true;
    }

    // Parse the given JSON object
    parseDocument(document) {
      if (typeof document === 'string' || document instanceof String) {
        return this.object = this.processDocument(document);
      }
      return this.object = document;
    }

    // Process the incoming JSON text document to JSON object
    processDocument(document) {
      try {
        return JSON.parse(document);
      } catch (error) {
        return {};
      }
    }

  };

  module.exports = Json;

}).call(this);
