// Generated by CoffeeScript 2.7.0
(function() {
  var XMLParser, Xml, _;

  _ = require('underscore');

  ({XMLParser} = require('fast-xml-parser'));

  // XML Response Parser
  Xml = class Xml {
    // XML parser initialization
    constructor() {
      this.object = {};
      this.parseRootNode = false;
      this.fastXmlParser = new XMLParser({
        ignoreDeclaration: true,
        ignoreAttributes: false,
        attributeNamePrefix: ''
      });
    }

    // Parsed Object to JSON
    getObject() {
      return this.object;
    }

    // Remove root element from the parsed structure
    skipRootNode() {
      return this.parseRootNode = true;
    }

    // Parse the given XML document
    parseDocument(document) {
      this.object = this.processDocument(document);
      if (this.parseRootNode) {
        this.object = this.removeFirstNode(this.object);
      }
      return this.object;
    }

    // Process the incoming XML document to JSON
    processDocument(document) {
      try {
        return this.fastXmlParser.parse(document);
      } catch (error) {
        return {};
      }
    }

    // Remove the firstChild as its usually just a single node
    removeFirstNode() {
      var keysCount;
      keysCount = _.keys(this.object).length;
      if (keysCount === 1 && this.object[_.keys(this.object)[0]] instanceof Object) {
        return this.object[_.first(_.keys(this.object))];
      }
      return this.object;
    }

  };

  module.exports = Xml;

}).call(this);
