// Generated by CoffeeScript 2.7.0
(function() {
  var Base, Reconcile;

  Base = require('../base');

  Reconcile = class Reconcile extends Base {
    constructor(params) {
      super(params);
    }

    getTransactionType() {
      return 'wpf_reconcile';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'wpf',
        path: 'wpf/reconcile'
      };
    }

    getTrxData() {
      return {
        'wpf_reconcile': this.params
      };
    }

  };

  module.exports = Reconcile;

}).call(this);
