// Generated by CoffeeScript 2.5.1
(function() {
  var Base, Reconcile;

  Base = require('../base');

  Reconcile = class Reconcile extends Base {
    constructor(params) {
      super(params);
      this.requiredFields = ['unique_id'];
    }

    getUrl() {
      return {
        app: 'wpf',
        path: 'wpf/reconcile'
      };
    }

    getTrxData() {
      return {
        'wpf_reconcile': this.params
      };
    }

  };

  module.exports = Reconcile;

}).call(this);
