// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, InstaDebitPayin, TransactionTypes, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  InstaDebitPayin = class InstaDebitPayin extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.INSTA_DEBIT_PAYIN;
    }

  };

  module.exports = InstaDebitPayin;

}).call(this);
