// Generated by CoffeeScript 2.5.1
(function() {
  var FinancialBase, InstaDebitPayin, StringValidator, TransactionTypes, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  StringValidator = require('../../../../helpers/validators/string_validator');

  InstaDebitPayin = class InstaDebitPayin extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.INSTA_DEBIT_PAYIN;
    }

    constructor(params) {
      super(params);
      this.requiredFields = _.union(this.requiredFields, ['return_url', 'customer_account_id', 'billing_address.country']);
      this.fieldsValues['transaction_id'] = new StringValidator(1, 30);
      this.fieldsValues['billing_address.country'] = ['CA'];
    }

  };

  module.exports = InstaDebitPayin;

}).call(this);
