// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, InstaDebitPayout, TransactionTypes, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  InstaDebitPayout = class InstaDebitPayout extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.INSTA_DEBIT_PAYOUT;
    }

  };

  module.exports = InstaDebitPayout;

}).call(this);
