// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, InstaDebitPayout, StringValidator, TransactionTypes, _;

  FinancialBase = require('../../financial_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  _ = require('underscore');

  StringValidator = require('../../../../helpers/validators/string_validator');

  InstaDebitPayout = class InstaDebitPayout extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.INSTA_DEBIT_PAYOUT;
    }

    constructor(params) {
      super(params);
      this.requiredFields = _.union(this.requiredFields, ['reference_id']);
      this.fieldsValues['transaction_id'] = new StringValidator(1, 30);
    }

  };

  module.exports = InstaDebitPayout;

}).call(this);
