// Generated by CoffeeScript 2.7.0
(function() {
  var CardTypes, _;

  _ = require('underscore');

  CardTypes = (function() {
    class CardTypes {
      getCardTypes() {
        var key, ref, results, value;
        ref = this.constructor;
        results = [];
        for (key in ref) {
          value = ref[key];
          results.push(value);
        }
        return results;
      }

      isValidCardType(type) {
        return _.indexOf(this.getCardTypes(), type) !== -1;
      }

    };

    /*
      The type of the issued card will be virtual
    */
    CardTypes.VIRTUAL = 'virtual';

    /*
      The type of the issued card will be physical
    */
    CardTypes.PHYSICAL = 'physical';

    return CardTypes;

  }).call(this);

  module.exports = CardTypes;

}).call(this);
