// Generated by CoffeeScript 2.7.0
(function() {
  var Detokenize, Request, TransactionTypes;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  Detokenize = (function() {
    class Detokenize extends Request {
      getTransactionType() {
        return TransactionTypes.DETOKENIZE;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.DETOKENIZE_URL
        };
      }

      getTrxData() {
        return {
          'detokenize_request': this.params
        };
      }

    };

    Detokenize.prototype.DETOKENIZE_URL = 'v1/detokenize';

    return Detokenize;

  }).call(this);

  module.exports = Detokenize;

}).call(this);
