// Generated by CoffeeScript 2.7.0
(function() {
  var AfricanMobileSale, FinancialBase, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  AfricanMobileSale = class AfricanMobileSale extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.AFRICAN_MOBILE_SALE;
    }

  };

  module.exports = AfricanMobileSale;

}).call(this);
