// Generated by CoffeeScript 2.7.0
(function() {
  var ApplePay, FinancialBase, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  ApplePay = class ApplePay extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.APPLE_PAY;
    }

    getTrxData() {
      super.getTrxData();
      return {
        'payment_transaction': _.extend(this.params, {
          'payment_token': JSON.stringify(this.params['payment_token'])
        })
      };
    }

  };

  module.exports = ApplePay;

}).call(this);
