// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, GooglePay, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  GooglePay = class GooglePay extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.GOOGLE_PAY;
    }

    getTrxData() {
      super.getTrxData();
      return {
        'payment_transaction': _.extend(this.params, {
          'payment_token': JSON.stringify(this.params['payment_token'])
        })
      };
    }

  };

  module.exports = GooglePay;

}).call(this);
