// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, RussianMobileSale, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  RussianMobileSale = class RussianMobileSale extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.RUSSIAN_MOBILE_SALE;
    }

  };

  module.exports = RussianMobileSale;

}).call(this);
