// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, Sale, TransactionTypes;

  AlternativeBase = require('../alternative_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  Sale = class Sale extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.TRUSTLY_SALE;
    }

  };

  module.exports = Sale;

}).call(this);
