// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, DateValidator, TransactionTypes, Withdrawal, _;

  AlternativeBase = require('../alternative_base');

  TransactionTypes = require('../../../../helpers/transaction/types');

  DateValidator = require('../../../../helpers/validators/date_validator');

  _ = require('underscore');

  Withdrawal = class Withdrawal extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.TRUSTLY_WITHDRAWAL;
    }

    constructor(params, configuration) {
      super(params, configuration);
      this.requiredFields = _.union(this.requiredFields, ['birth_date']);
      this.fieldsValues = {
        'birth_date': new DateValidator('DD-MM-YYYY')
      };
    }

  };

  module.exports = Withdrawal;

}).call(this);
