// Generated by CoffeeScript 2.7.0
(function() {

  /*
    Check the status of a specific Brazilian company's CNPJ number.
    The CNPJ number is provided in the request URL as a parameter.
  */
  var KycCnpj, Request, util;

  Request = require('../../../../request');

  util = require('util');

  KycCnpj = (function() {
    var CNPJ;

    class KycCnpj extends Request {
      constructor(params, configuration) {
        super(params, configuration, 'json');
        this.populateIdentifier();
      }

      getTransactionType() {
        return 'kyc_cnpj';
      }

      getData() {
        return this.params;
      }

      getUrl() {
        return {
          app: 'kyc',
          path: util.format(CNPJ, this.documentId)
        };
      }

      getTrxData() {
        return this.params;
      }

      // Populate Document ID used in the endpoint
      populateIdentifier() {
        this.documentId = '';
        return this.documentId = this.params instanceof Object && this.params.hasOwnProperty('document_id') ? this.params.document_id : void 0;
      }

    };

    CNPJ = '/api/v1/cnpj/%s';

    return KycCnpj;

  }).call(this);

  module.exports = KycCnpj;

}).call(this);
