// Generated by CoffeeScript 2.7.0
(function() {
  var CreatePayeeAccount, Request, _;

  Request = require('../../../request');

  _ = require('underscore');

  /*
    Create an Account related to a specific Payee
  */
  CreatePayeeAccount = class CreatePayeeAccount extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'json');
      this.populateIdentifier();
    }

    getTransactionType() {
      return 'create_payee_account';
    }

    // Request endpoint
    getUrl() {
      return {
        app: 'smart_router',
        path: `payee/${this.payee_unique_id}/account`
      };
    }

    getTrxData() {
      delete this.params.payee_unique_id;
      return this.params;
    }

    // Populate Payee ID used in the endpoint
    populateIdentifier() {
      this.payee_unique_id = '';
      if (this.params instanceof Object && this.params.hasOwnProperty('payee_unique_id')) {
        return this.payee_unique_id = this.params.payee_unique_id;
      }
    }

  };

  module.exports = CreatePayeeAccount;

}).call(this);
