// Generated by CoffeeScript 2.7.0
(function() {
  var CreatePayee, Request;

  Request = require('../../../request');

  /*
    Create a Payee record
  */
  CreatePayee = class CreatePayee extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'json');
    }

    getTransactionType() {
      return 'create_payee';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'smart_router',
        path: 'payee'
      };
    }

    getTrxData() {
      return {
        'payee': this.params
      };
    }

  };

  module.exports = CreatePayee;

}).call(this);
