// Generated by CoffeeScript 2.7.0
(function() {
  var ListPayeeAccounts, Request, URLSearchParams, _;

  Request = require('../../../request');

  _ = require('underscore');

  ({URLSearchParams} = require('url'));

  /*
    Retrieve the details of all Account records that belongs to specific Payee
  */
  ListPayeeAccounts = class ListPayeeAccounts extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'get');
      this.populateURLparameters();
    }

    getTransactionType() {
      return 'list_payee_accounts';
    }

    // Request endpoint
    getUrl() {
      return {
        app: 'smart_router',
        path: `payee/${this.payee_unique_id}/account${this.additional_params}`
      };
    }

    // Populate parameters used in the endpoint
    populateURLparameters() {
      var params;
      this.payee_unique_id = '';
      if (this.params instanceof Object && this.params.hasOwnProperty('payee_unique_id')) {
        this.payee_unique_id = this.params.payee_unique_id;
      }
      params = _.omit(this.params, 'payee_unique_id');
      this.additional_params = '';
      if (!_.isEmpty(params)) {
        return this.additional_params = `/?${new URLSearchParams(params)}`;
      }
    }

  };

  module.exports = ListPayeeAccounts;

}).call(this);
