// Generated by CoffeeScript 2.7.0
(function() {
  var Request, RetrievePayee;

  Request = require('../../../request');

  /*
    Retrieve the details of a specific a Payee record based on its unique ID
  */
  RetrievePayee = class RetrievePayee extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'get');
      this.populateIdentifier();
    }

    getTransactionType() {
      return 'retrieve_payee';
    }

    // Request endpoint
    getUrl() {
      return {
        app: 'smart_router',
        path: `payee/${this.identifier}`
      };
    }

    // Populate Payee ID used in the endpoint
    populateIdentifier() {
      this.identifier = '';
      if (this.params instanceof Object && this.params.hasOwnProperty('payee_unique_id')) {
        return this.identifier = this.params.payee_unique_id;
      }
    }

  };

  module.exports = RetrievePayee;

}).call(this);
