// Generated by CoffeeScript 2.7.0
(function() {
  var Baloto, FinancialBase, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Baloto = class Baloto extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.BALOTO;
    }

  };

  module.exports = Baloto;

}).call(this);
