// Generated by CoffeeScript 2.7.0
(function() {
  var BancoDeOccidente, FinancialBase, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  BancoDeOccidente = class BancoDeOccidente extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.BANCO_DE_OCCIDENTE;
    }

  };

  module.exports = BancoDeOccidente;

}).call(this);
