// Generated by CoffeeScript 2.7.0
(function() {
  var Boleto, FinancialBase, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Boleto = class Boleto extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.BOLETO;
    }

  };

  module.exports = Boleto;

}).call(this);
