// Generated by CoffeeScript 2.7.0
(function() {
  var Cash, FinancialBase, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Cash = class Cash extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.CASH;
    }

  };

  module.exports = Cash;

}).call(this);
