// Generated by CoffeeScript 2.7.0
(function() {
  var Efecty, FinancialBase, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Efecty = class Efecty extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.EFECTY;
    }

  };

  module.exports = Efecty;

}).call(this);
