// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Oxxo, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Oxxo = class Oxxo extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.OXXO;
    }

  };

  module.exports = Oxxo;

}).call(this);
