// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, PagoFacil, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  PagoFacil = class PagoFacil extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.PAGO_FACIL;
    }

  };

  module.exports = PagoFacil;

}).call(this);
