// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Pix, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Pix = class Pix extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.PIX;
    }

  };

  module.exports = Pix;

}).call(this);
