// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Redpagos, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  Redpagos = class Redpagos extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.REDPAGOS;
    }

  };

  module.exports = Redpagos;

}).call(this);
