// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, PayPal, TransactionTypes, _;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  PayPal = class PayPal extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.PAY_PAl;
    }

  };

  module.exports = PayPal;

}).call(this);
