// Generated by CoffeeScript 2.7.0
(function() {
  var BicValidator, IbanValidator, NumberValidator, SddBase, SddSale, StringValidator, TransactionTypes, _;

  SddBase = require('./sdd_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  StringValidator = require('../../../helpers/validators/string_validator');

  NumberValidator = require('../../../helpers/validators/number_validator');

  IbanValidator = require('../../../helpers/validators/iban_validator');

  BicValidator = require('../../../helpers/validators/bic_validator');

  _ = require('underscore');

  SddSale = class SddSale extends SddBase {
    getTransactionType() {
      return TransactionTypes.SDD_SALE;
    }

    constructor(params) {
      super(params);
    }

  };

  module.exports = SddSale;

}).call(this);
