// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, SddBase;

  FinancialBase = require('../financial_base');

  SddBase = class SddBase extends FinancialBase {};

  module.exports = SddBase;

}).call(this);
