// Generated by CoffeeScript 2.7.0
(function() {
  var SddBase, SddRefund, TransactionTypes;

  SddBase = require('./sdd_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  SddRefund = class SddRefund extends SddBase {
    getTransactionType() {
      return TransactionTypes.SDD_REFUND;
    }

  };

  module.exports = SddRefund;

}).call(this);
