// Generated by CoffeeScript 2.5.1
(function() {
  var SddBase, SddRecurringSale, TransactionTypes, _;

  SddBase = require('./sdd_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  SddRecurringSale = class SddRecurringSale extends SddBase {
    getTransactionType() {
      return TransactionTypes.SDD_RECURRING_SALE;
    }

    constructor(params) {
      super(params);
      this.requiredFields = _.union(this.requiredFields, ['usage', 'reference_id']);
    }

  };

  module.exports = SddRecurringSale;

}).call(this);
