// Generated by CoffeeScript 2.7.0
(function() {
  var SddBase, SddInitRecurringSale, TransactionTypes;

  SddBase = require('./sdd_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  SddInitRecurringSale = class SddInitRecurringSale extends SddBase {
    getTransactionType() {
      return TransactionTypes.SDD_INIT_RECURRING_SALE;
    }

  };

  module.exports = SddInitRecurringSale;

}).call(this);
