// Generated by CoffeeScript 2.7.0
(function() {
  var SddBase, SddSale, TransactionTypes;

  SddBase = require('./sdd_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  SddSale = class SddSale extends SddBase {
    getTransactionType() {
      return TransactionTypes.SDD_SALE;
    }

  };

  module.exports = SddSale;

}).call(this);
