// Generated by CoffeeScript 2.7.0
(function() {
  var SddBase, SddRefund, TransactionTypes, _;

  SddBase = require('./sdd_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  SddRefund = class SddRefund extends SddBase {
    getTransactionType() {
      return TransactionTypes.SDD_REFUND;
    }

    constructor(params) {
      super(params);
    }

  };

  module.exports = SddRefund;

}).call(this);
