// Generated by CoffeeScript 2.5.1
(function() {
  var BicValidator, IbanValidator, SddBase, SddInitRecurringSale, StringValidator, TransactionTypes, _;

  SddBase = require('./sdd_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  StringValidator = require('../../../helpers/validators/string_validator');

  IbanValidator = require('../../../helpers/validators/iban_validator');

  BicValidator = require('../../../helpers/validators/bic_validator');

  _ = require('underscore');

  SddInitRecurringSale = class SddInitRecurringSale extends SddBase {
    getTransactionType() {
      return TransactionTypes.SDD_INIT_RECURRING_SALE;
    }

    constructor(params) {
      super(params);
      this.requiredFields = _.union(this.requiredFields, ['usage', 'billing_address.first_name', 'billing_address.last_name', 'billing_address.country', 'iban', 'bic']);
      this.fieldsValues = _.extend(this.fieldsValues, {
        'iban': new IbanValidator(),
        'bic': new BicValidator()
      });
    }

  };

  module.exports = SddInitRecurringSale;

}).call(this);
