// Generated by CoffeeScript 2.5.1
(function() {
  var FinancialBase, NumberValidator, SddBase, _;

  FinancialBase = require('../financial_base');

  NumberValidator = require('../../../helpers/validators/number_validator');

  _ = require('underscore');

  SddBase = class SddBase extends FinancialBase {
    constructor(params) {
      super(params);
      this.fieldsValues = _.extend(this.fieldsValues, {
        'amount': new NumberValidator(10, 24999.99)
      });
    }

  };

  module.exports = SddBase;

}).call(this);
