// Generated by CoffeeScript 2.7.0
(function() {
  var AxiosApi, BaseRequestApi, Promise, _, axios, config, https, util;

  _ = require('underscore');

  util = require('util');

  config = require('config');

  axios = require('axios');

  https = require('https');

  BaseRequestApi = require('./base_request_api');

  Promise = require('bluebird');

  AxiosApi = class AxiosApi extends BaseRequestApi {
    constructor() {
      super();
    }

    request_query(url, requestConfig, params) {
      var requestObject;
      requestObject = Object.assign({
        url: url,
        data: params
      }, requestConfig);
      return this.doRequest(axios, requestObject);
    }

  };

  module.exports = AxiosApi;

}).call(this);
