// Generated by CoffeeScript 2.7.0
(function() {
  var KycUpdateConsumer, Request;

  Request = require('../../../../request');

  /*
    Update the customer registration to be able to pass on the latest status required so
    we can continue improving the data models and provide the best scores and recommendations
    possible.
  */
  KycUpdateConsumer = class KycUpdateConsumer extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'json');
    }

    getTransactionType() {
      return 'kyc_update_consumer';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'kyc',
        path: 'api/v1/update_consumer'
      };
    }

    getTrxData() {
      return this.params;
    }

  };

  module.exports = KycUpdateConsumer;

}).call(this);
