// Generated by CoffeeScript 2.7.0
(function() {
  var KycCreateConsumer, Request;

  Request = require('../../../../request');

  /*
    Review all aspects of the customer’s information, as it is received in the registration
    process, against local and external databases to increase accuracy and produce a risk score
    for that customer.
  */
  KycCreateConsumer = class KycCreateConsumer extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'json');
    }

    getTransactionType() {
      return 'kyc_create_consumer';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'kyc',
        path: 'api/v1/create_consumer'
      };
    }

    getTrxData() {
      return this.params;
    }

  };

  module.exports = KycCreateConsumer;

}).call(this);
