// Generated by CoffeeScript 2.7.0
(function() {
  var Builder, Form, Json, Xml;

  Xml = require('./builders/xml');

  Form = require('./builders/form');

  Json = require('./builders/json');

  Builder = (function() {
    class Builder {
      constructor(builderInterface) {
        switch (builderInterface) {
          case this.XML:
            this.context = new Xml();
            break;
          case this.FORM:
            this.context = new Form();
            break;
          case this.JSON:
            this.context = new Json();
            break;
          default:
            this.context = null;
        }
      }

      getDocument(structure) {
        if (this.context === null) {
          return '';
        }
        return this.context.buildStructure(structure);
      }

    };

    // XML Builder Identifier
    Builder.prototype.XML = 'xml';

    // JSON Builder Identifier
    Builder.prototype.JSON = 'json';

    // FORM Builder Identifier
    Builder.prototype.FORM = 'form';

    return Builder;

  }).call(this);

  module.exports = Builder;

}).call(this);
