// Generated by CoffeeScript 2.7.0
(function() {
  var Json, Parser, Xml;

  Xml = require('./parsers/xml');

  Json = require('./parsers/json');

  Parser = (function() {
    // Response Parser wrapper
    class Parser {
      // Response Parser constructor
      constructor(parserInterface = this.XML_INTERFACE) {
        this.context = null;
        this.initParser(parserInterface);
      }

      // Parsed document
      getObject() {
        return this.context.getObject();
      }

      // Skip first node of the parsed JSON object
      skipRootNode() {
        return this.context.skipRootNode();
      }

      // Parse the given document into JSON object
      parseDocument(document) {
        return this.context.parseDocument(document);
      }

      // Parser factory
      initParser(parserInterface) {
        switch (parserInterface) {
          case this.JSON_INTERFACE:
            return this.context = new Json();
          case this.XML_INTERFACE:
            return this.context = new Xml();
          default:
            throw Error("Invalid Parser Interface given!");
        }
      }

    };

    // XML Interface
    Parser.prototype.XML_INTERFACE = 'xml';

    // JSON interface
    Parser.prototype.JSON_INTERFACE = 'json';

    return Parser;

  }).call(this);

  module.exports = Parser;

}).call(this);
