// Generated by CoffeeScript 2.7.0
(function() {
  var Currency, Response, _, fastXmlParser;

  _ = require('underscore');

  fastXmlParser = require('fast-xml-parser');

  Currency = require('./helpers/currency');

  Response = class Response {
    constructor() {
      this.setUnderscoreMixins();
    }

    /*
      Attempt to process response from Genesis Payment Gateway
    */
    process(response) {
      return _.chain(response.data).response_parse().response_flatten().response_convert_amount().value();
    }

    /*
      Add the processing steps as underscore.js mix-ins
    */
    setUnderscoreMixins() {
      return _.mixin({
        // Parse the incoming XML document to JSON
        response_parse: function(xml) {
          return fastXmlParser.parse(xml, []);
        },
        // Remove the firstChild as its usually just a single node
        response_flatten: function(responseObject) {
          return responseObject[_.first(_.keys(responseObject))];
        },
        // Convert the amount from ISO4217 to Nominal
        response_convert_amount: function(responseObject) {
          var currency;
          currency = new Currency();
          if (responseObject.hasOwnProperty('amount') && responseObject.hasOwnProperty('currency')) {
            responseObject.amount = currency.convertToNominalUnits(responseObject.amount, responseObject.currency);
          }
          return responseObject;
        }
      });
    }

  };

  module.exports = Response;

}).call(this);
