// Generated by CoffeeScript 2.7.0
(function() {
  var Currency, Response, XMLParser, _;

  _ = require('underscore');

  ({XMLParser} = require('fast-xml-parser'));

  Currency = require('./helpers/currency');

  Response = class Response {
    constructor() {
      this.fastXmlParser = new XMLParser({
        ignoreDeclaration: true
      });
      this.setUnderscoreMixins();
    }

    /*
      Attempt to process response from Genesis Payment Gateway
    */
    process(response) {
      return _.chain(response.data).response_parse(this.fastXmlParser).response_flatten().response_convert_amount().value();
    }

    /*
      Add the processing steps as underscore.js mix-ins
    */
    setUnderscoreMixins() {
      return _.mixin({
        // Parse the incoming XML document to JSON
        response_parse: function(xml, fastXmlParser) {
          return fastXmlParser.parse(xml);
        },
        // Remove the firstChild as its usually just a single node
        response_flatten: function(responseObject) {
          return responseObject[_.first(_.keys(responseObject))];
        },
        // Convert the amount from ISO4217 to Nominal
        response_convert_amount: function(responseObject) {
          var currency;
          currency = new Currency();
          if (responseObject !== void 0) {
            if (responseObject.hasOwnProperty('amount') && responseObject.hasOwnProperty('currency')) {
              responseObject.amount = currency.convertToNominalUnits(responseObject.amount, responseObject.currency);
            }
          }
          return responseObject;
        }
      });
    }

  };

  module.exports = Response;

}).call(this);
