// Generated by CoffeeScript 2.7.0
(function() {

  /*
    Financial Payout transactions
  */
  /*
    Financial transactions
  */
  /*
    CashPayment
  */
  /*
    Vouchers
  */
  /*
    Non Financial transactions
  */
  /*
    FX Services
  */
  /*
    Financial mobile transactions
  */
  /*
    Installments API services
  */
  /*
    KYC Services
  */
  /*
    MethodContinue
  */
  /*
    Financial Alternative transactions
  */
  /*
    Financial payout transactions
  */
  /*
    SCA
  */
  /*
    Direct Debit
  */
  /*
    Tokenization
  */
  /*
    Financial OBP transactions
  */
  /*
    Web Payment Form
  */
  var AfricanMobilePayout, AfricanMobileSale, Alipay, ApplePay, Argencard, Aura, Authorize, Authorize3d, Baloto, BancoDeOccidente, BancoDoBrasil, Bancomer, Bancontact, Blacklist, Boleto, Bradesco, Cabal, Cancel, Capture, Cash, CashU, Cencosud, Chargeback, ChargebackByDate, Config, CreateConsumer, Credit, Davivienda, DeleteToken, Detokenize, DisableConsumer, Efecty, Elo, EnableConsumer, Eps, FraudReport, FraudReportByDate, FxRate, FxRates, FxSearchRate, FxTier, FxTiers, GetCards, GetTokenizedCard, GooglePay, IDebitPayin, IDebitPayout, Ideal, InitRecurringSale, InitRecurringSale3d, InstaDebitPayin, InstaDebitPayout, InstallmentsFetch, InstallmentsShowDetails, Itau, KycCnpj, KycCpf, KycCreateConsumer, KycCreateTransaction, KycCreateVerification, KycDownloadDocument, KycMakeCall, KycUpdateCall, KycUpdateConsumer, KycUpdateTransaction, KycUploadDocument, KycVerificationRegister, KycVerificationStatus, MethodContinue, Multibanco, MyBank, Naranja, Nativa, OnlineBankingPayin, OnlineBankingPayout, Oxxo, P24, PPRO, PagoFacil, PayPal, Payers, Payout, Paysafecard, Payu, Pix, Poli, PostFinance, ProcessedTransactions, ProcessedTransactionsByDate, ProcessedTransactionsByPostDate, Pse, Reconcile, ReconcileByDate, RecurringSale, Redpagos, Refund, Retrieval, RetrievalByDate, RetrieveConsumer, RussianMobilePayout, RussianMobileSale, Sale, Sale3d, Santander, ScaChecker, SddInitRecurringSale, SddRecurringSale, SddRefund, SddSale, Sofort, TarjetaShopping, Tokenize, Transaction, TrustlySale, TrustlyWithdrawal, UpdateConsumer, UpdateToken, ValidateToken, Webpay, Wechat, WpfCreate, WpfReconcile;

  Config = require('./utils/configuration/config');

  Aura = require('./transactions/financial/cards/aura');

  Argencard = require('./transactions/financial/cards/argencard');

  Authorize = require('./transactions/financial/cards/authorize');

  Authorize3d = require('./transactions/financial/cards/authorize3d');

  Bancontact = require('./transactions/financial/cards/bancontact');

  Cabal = require('./transactions/financial/cards/cabal');

  Cencosud = require('./transactions/financial/cards/cencosud');

  Elo = require('./transactions/financial/cards/elo');

  Sale = require('./transactions/financial/cards/sale');

  Sale3d = require('./transactions/financial/cards/sale3d');

  Cancel = require('./transactions/financial/cancel');

  Payout = require('./transactions/financial/cards/payout');

  Credit = require('./transactions/financial/cards/credit');

  RecurringSale = require('./transactions/financial/cards/recurring/recurring_sale');

  InitRecurringSale = require('./transactions/financial/cards/recurring/init_recurring_sale');

  InitRecurringSale3d = require('./transactions/financial/cards/recurring/init_recurring_sale3d');

  Capture = require('./transactions/financial/capture');

  Refund = require('./transactions/financial/refund');

  Nativa = require('./transactions/financial/cards/nativa');

  Naranja = require('./transactions/financial/cards/naranja');

  TarjetaShopping = require('./transactions/financial/cards/tarjeta_shopping');

  Cash = require('./transactions/financial/cash_payments/cash');

  BancoDeOccidente = require('./transactions/financial/cash_payments/banco_de_occidente');

  Baloto = require('./transactions/financial/cash_payments/baloto');

  Boleto = require('./transactions/financial/cash_payments/boleto');

  Efecty = require('./transactions/financial/cash_payments/efecty');

  Oxxo = require('./transactions/financial/cash_payments/oxxo');

  PagoFacil = require('./transactions/financial/cash_payments/pago_facil');

  Pix = require('./transactions/financial/cash_payments/pix');

  Redpagos = require('./transactions/financial/cash_payments/redpagos');

  Chargeback = require('./transactions/non_financial/fraud/chargeback/chargeback');

  ChargebackByDate = require('./transactions/non_financial/fraud/chargeback/chargeback_by_date');

  Blacklist = require('./transactions/non_financial/blacklist');

  FraudReport = require('./transactions/non_financial/fraud/reports/fraud_report');

  FraudReportByDate = require('./transactions/non_financial/fraud/reports/fraud_report_by_date');

  Retrieval = require('./transactions/non_financial/fraud/retrieval/retrieval');

  RetrievalByDate = require('./transactions/non_financial/fraud/retrieval/retrieval_by_date');

  Reconcile = require('./transactions/non_financial/reconcile/reconcile');

  ReconcileByDate = require('./transactions/non_financial/reconcile/reconcile_by_date');

  Payers = require('./transactions/non_financial/alternatives/transfer_to/payers');

  CreateConsumer = require('./transactions/non_financial/consumers/create');

  UpdateConsumer = require('./transactions/non_financial/consumers/update');

  DisableConsumer = require('./transactions/non_financial/consumers/disable');

  EnableConsumer = require('./transactions/non_financial/consumers/enable');

  GetCards = require('./transactions/non_financial/consumers/get_cards');

  RetrieveConsumer = require('./transactions/non_financial/consumers/retrieve');

  ProcessedTransactions = require('./transactions/non_financial/processed_transactions/processed_transactions');

  ProcessedTransactionsByDate = require('./transactions/non_financial/processed_transactions/processed_transactions_by_date');

  ProcessedTransactionsByPostDate = require('./transactions/non_financial/processed_transactions/processed_transactions_by_post_date');

  WpfCreate = require('./transactions/wpf/create');

  WpfReconcile = require('./transactions/wpf/reconcile');

  Paysafecard = require('./transactions/financial/alternative/paysafecard');

  Sofort = require('./transactions/financial/alternative/sofort');

  PPRO = require('./transactions/financial/alternative/ppro');

  TrustlySale = require('./transactions/financial/alternative/trustly/sale');

  TrustlyWithdrawal = require('./transactions/financial/alternative/trustly/withdrawal');

  Wechat = require('./transactions/financial/obp/wechat');

  Alipay = require('./transactions/financial/obp/alipay');

  IDebitPayin = require('./transactions/financial/obp/idebit/payin');

  IDebitPayout = require('./transactions/financial/obp/idebit/payout');

  InstaDebitPayin = require('./transactions/financial/obp/insta_debit/payin');

  InstaDebitPayout = require('./transactions/financial/obp/insta_debit/payout');

  OnlineBankingPayin = require('./transactions/financial/obp/online_banking/payin');

  OnlineBankingPayout = require('./transactions/financial/obp/online_banking/payout');

  MyBank = require('./transactions/financial/obp/my_bank');

  Bancomer = require('./transactions/financial/obp/bancomer');

  BancoDoBrasil = require('./transactions/financial/obp/banco_do_brasil');

  Bradesco = require('./transactions/financial/obp/bradesco');

  Davivienda = require('./transactions/financial/obp/davivienda');

  Eps = require('./transactions/financial/obp/eps');

  Itau = require('./transactions/financial/obp/itau');

  Multibanco = require('./transactions/financial/obp/multibanco');

  P24 = require('./transactions/financial/obp/p24');

  Ideal = require('./transactions/financial/obp/ideal');

  Payu = require('./transactions/financial/obp/payu');

  Poli = require('./transactions/financial/obp/poli');

  Pse = require('./transactions/financial/obp/pse');

  PostFinance = require('./transactions/financial/obp/post_finance');

  Santander = require('./transactions/financial/obp/santander');

  Webpay = require('./transactions/financial/obp/webpay');

  SddSale = require('./transactions/financial/direct_debit/sdd_sale');

  SddInitRecurringSale = require('./transactions/financial/direct_debit/sdd_init_recurring_sale');

  SddRecurringSale = require('./transactions/financial/direct_debit/sdd_recurring_sale');

  SddRefund = require('./transactions/financial/direct_debit/sdd_refund');

  GooglePay = require('./transactions/financial/mobile/google_pay');

  ApplePay = require('./transactions/financial/mobile/apple_pay');

  AfricanMobileSale = require('./transactions/financial/mobile/african_mobile_sale');

  PayPal = require('./transactions/financial/wallets/pay_pal');

  RussianMobileSale = require('./transactions/financial/mobile/russian_mobile_sale');

  AfricanMobilePayout = require('./transactions/financial/payout/african_mobile_payout');

  RussianMobilePayout = require('./transactions/financial/payout/russian_mobile_payout');

  CashU = require('./transactions/financial/vouchers/cashu');

  MethodContinue = require('./transactions/financial/cards/threeds/v2/method_continue');

  OnlineBankingPayin = require('./transactions/financial/obp/online_banking/payin');

  Tokenize = require('./transactions/non_financial/tokenization/tokenize');

  UpdateToken = require('./transactions/non_financial/tokenization/update_token');

  Detokenize = require('./transactions/non_financial/tokenization/detokenize');

  ValidateToken = require('./transactions/non_financial/tokenization/validate_token');

  DeleteToken = require('./transactions/non_financial/tokenization/delete_token');

  GetTokenizedCard = require('./transactions/non_financial/tokenization/get_tokenized_card');

  FxTier = require('./transactions/non_financial/fx/tier');

  FxTiers = require('./transactions/non_financial/fx/tiers');

  FxRate = require('./transactions/non_financial/fx/rate');

  FxRates = require('./transactions/non_financial/fx/rates');

  FxSearchRate = require('./transactions/non_financial/fx/search_rate');

  KycCreateConsumer = require('./transactions/non_financial/kyc/consumer_registration/kyc_create_consumer');

  KycUpdateConsumer = require('./transactions/non_financial/kyc/consumer_registration/kyc_update_consumer');

  KycCreateTransaction = require('./transactions/non_financial/kyc/transaction/kyc_create_transaction');

  KycUpdateTransaction = require('./transactions/non_financial/kyc/transaction/kyc_update_transaction');

  KycUploadDocument = require('./transactions/non_financial/kyc/identity_document/kyc_upload_document');

  KycDownloadDocument = require('./transactions/non_financial/kyc/identity_document/kyc_download_document');

  KycMakeCall = require('./transactions/non_financial/kyc/call/kyc_make_call');

  KycUpdateCall = require('./transactions/non_financial/kyc/call/kyc_update_call');

  KycCreateVerification = require('./transactions/non_financial/kyc/verification/kyc_create_verification');

  KycVerificationStatus = require('./transactions/non_financial/kyc/verification/kyc_verification_status');

  KycVerificationRegister = require('./transactions/non_financial/kyc/verification/kyc_verification_register');

  KycCpf = require('./transactions/non_financial/kyc/cpf/kyc_cpf');

  KycCnpj = require('./transactions/non_financial/kyc/cnpj/kyc_cnpj');

  ScaChecker = require('./transactions/non_financial/sca/checker');

  InstallmentsFetch = require('./transactions/non_financial/installments/fetch');

  InstallmentsShowDetails = require('./transactions/non_financial/installments/show_details');

  /*
    Library Transaction factory
  */
  Transaction = class Transaction {
    constructor(configuration = null) {
      this.config = new Config(configuration);
    }

    /*
      Financial Alternative transactions
    */
    p24(params) {
      return new P24(params, this.config);
    }

    poli(params) {
      return new Poli(params, this.config);
    }

    paysafecard(params) {
      return new Paysafecard(params, this.config);
    }

    sofort(params) {
      return new Sofort(params, this.config);
    }

    ppro(params) {
      return new PPRO(params, this.config);
    }

    trustly_sale(params) {
      return new TrustlySale(params, this.config);
    }

    trustly_withdrawal(params) {
      return new TrustlyWithdrawal(params, this.config);
    }

    cashu(params) {
      return new CashU(params, this.config);
    }

    /*
      Financial transactions
    */
    aura(params) {
      return new Aura(params, this.config);
    }

    argencard(params) {
      return new Argencard(params, this.config);
    }

    authorize(params) {
      return new Authorize(params, this.config);
    }

    authorize3d(params) {
      return new Authorize3d(params, this.config);
    }

    bcmc(params) {
      return new Bancontact(params, this.config);
    }

    cabal(params) {
      return new Cabal(params, this.config);
    }

    cencosud(params) {
      return new Cencosud(params, this.config);
    }

    credit(params) {
      return new Credit(params, this.config);
    }

    elo(params) {
      return new Elo(params, this.config);
    }

    init_recurring_sale(params) {
      return new InitRecurringSale(params, this.config);
    }

    init_recurring_sale3d(params) {
      return new InitRecurringSale3d(params, this.config);
    }

    recurring_sale(params) {
      return new RecurringSale(params, this.config);
    }

    payout(params) {
      return new Payout(params, this.config);
    }

    sale(params) {
      return new Sale(params, this.config);
    }

    sale3d(params) {
      return new Sale3d(params, this.config);
    }

    cancel(params) {
      return new Cancel(params, this.config);
    }

    // keep this for backward compatibility
    void(params) {
      return this.cancel(params, this.config);
    }

    capture(params) {
      return new Capture(params, this.config);
    }

    refund(params) {
      return new Refund(params, this.config);
    }

    method_continue(params) {
      return new MethodContinue(params, this.config);
    }

    nativa(params) {
      return new Nativa(params, this.config);
    }

    naranja(params) {
      return new Naranja(params, this.config);
    }

    tarjeta_shopping(params) {
      return new TarjetaShopping(params, this.config);
    }

    /*
      Cash Payments transactions
    */
    baloto(params) {
      return new Baloto(params, this.config);
    }

    banco_de_occidente(params) {
      return new BancoDeOccidente(params, this.config);
    }

    boleto(params) {
      return new Boleto(params, this.config);
    }

    cash(params) {
      return new Cash(params, this.config);
    }

    efecty(params) {
      return new Efecty(params, this.config);
    }

    oxxo(params) {
      return new Oxxo(params, this.config);
    }

    pago_facil(params) {
      return new PagoFacil(params, this.config);
    }

    pix(params) {
      return new Pix(params, this.config);
    }

    redpagos(params) {
      return new Redpagos(params, this.config);
    }

    /*
      Direct Debit
    */
    sdd_sale(params) {
      return new SddSale(params, this.config);
    }

    sdd_init_recurring_sale(params) {
      return new SddInitRecurringSale(params, this.config);
    }

    sdd_recurring_sale(params) {
      return new SddRecurringSale(params, this.config);
    }

    sdd_refund(params) {
      return new SddRefund(params, this.config);
    }

    /*
      Financial mobile transactions
    */
    google_pay(params) {
      return new GooglePay(params, this.config);
    }

    african_mobile_sale(params) {
      return new AfricanMobileSale(params, this.config);
    }

    apple_pay(params) {
      return new ApplePay(params, this.config);
    }

    russian_mobile_sale(params) {
      return new RussianMobileSale(params, this.config);
    }

    /*
      Financial payout transactions
    */
    russian_mobile_payout(params) {
      return new RussianMobilePayout(params, this.config);
    }

    /*
      Financial OBP transactions
    */
    wechat(params) {
      return new Wechat(params, this.config);
    }

    alipay(params) {
      return new Alipay(params, this.config);
    }

    idebit_payin(params) {
      return new IDebitPayin(params, this.config);
    }

    idebit_payout(params) {
      return new IDebitPayout(params, this.config);
    }

    insta_debit_payin(params) {
      return new InstaDebitPayin(params, this.config);
    }

    insta_debit_payout(params) {
      return new InstaDebitPayout(params, this.config);
    }

    bradesco(params) {
      return new Bradesco(params, this.config);
    }

    davivienda(params) {
      return new Davivienda(params, this.config);
    }

    eps(params) {
      return new Eps(params, this.config);
    }

    itau(params) {
      return new Itau(params, this.config);
    }

    multibanco(params) {
      return new Multibanco(params, this.config);
    }

    ideal(params) {
      return new Ideal(params, this.config);
    }

    payu(params) {
      return new Payu(params, this.config);
    }

    pse(params) {
      return new Pse(params, this.config);
    }

    post_finance(params) {
      return new PostFinance(params, this.config);
    }

    santander(params) {
      return new Santander(params, this.config);
    }

    online_banking_payin(params) {
      return new OnlineBankingPayin(params, this.config);
    }

    online_banking_payout(params) {
      return new OnlineBankingPayout(params, this.config);
    }

    my_bank(params) {
      return new MyBank(params, this.config);
    }

    bancomer(params) {
      return new Bancomer(params, this.config);
    }

    banco_do_brasil(params) {
      return new BancoDoBrasil(params, this.config);
    }

    webpay(params) {
      return new Webpay(params, this.config);
    }

    /*
      Financial Payout transactions
    */
    african_mobile_payout(params) {
      return new AfricanMobilePayout(params, this.config);
    }

    /*
      Financial Wallets transactions
    */
    pay_pal(params) {
      return new PayPal(params, this.config);
    }

    /*
      Non Financial transactions
    */
    blacklist(params) {
      return new Blacklist(params, this.config);
    }

    chargeback(params) {
      return new Chargeback(params, this.config);
    }

    chargeback_by_date(params) {
      return new ChargebackByDate(params, this.config);
    }

    fraud_report(params) {
      return new FraudReport(params, this.config);
    }

    fraud_report_by_date(params) {
      return new FraudReportByDate(params, this.config);
    }

    retrieval(params) {
      return new Retrieval(params, this.config);
    }

    retrieval_by_date(params) {
      return new RetrievalByDate(params, this.config);
    }

    reconcile(params) {
      return new Reconcile(params, this.config);
    }

    reconcile_by_date(params) {
      return new ReconcileByDate(params, this.config);
    }

    transfer_to_payers() {
      return new Payers(null, this.config);
    }

    create_consumer(params) {
      return new CreateConsumer(params, this.config);
    }

    update_consumer(params) {
      return new UpdateConsumer(params, this.config);
    }

    disable_consumer(params) {
      return new DisableConsumer(params, this.config);
    }

    enable_consumer(params) {
      return new EnableConsumer(params, this.config);
    }

    get_consumer_cards(params) {
      return new GetCards(params, this.config);
    }

    retrieve_consumer(params) {
      return new RetrieveConsumer(params, this.config);
    }

    processed_transactions(params) {
      return new ProcessedTransactions(params, this.config);
    }

    processed_transactions_by_date(params) {
      return new ProcessedTransactionsByDate(params, this.config);
    }

    processed_transactions_by_post_date(params) {
      return new ProcessedTransactionsByPostDate(params, this.config);
    }

    /*
      Tokenization
    */
    tokenize(params) {
      return new Tokenize(params, this.config);
    }

    update_token(params) {
      return new UpdateToken(params, this.config);
    }

    detokenize(params) {
      return new Detokenize(params, this.config);
    }

    validate_token(params) {
      return new ValidateToken(params, this.config);
    }

    delete_token(params) {
      return new DeleteToken(params, this.config);
    }

    get_tokenized_card(params) {
      return new GetTokenizedCard(params, this.config);
    }

    /*
      FX
    */
    fx_tier(params) {
      return new FxTier(params, this.config);
    }

    fx_tiers() {
      return new FxTiers(null, this.config);
    }

    fx_rate(params) {
      return new FxRate(params, this.config);
    }

    fx_rates(params) {
      return new FxRates(params, this.config);
    }

    fx_search_rate(params) {
      return new FxSearchRate(params, this.config);
    }

    /*
      KYC services
    */
    kyc_create_consumer(params) {
      return new KycCreateConsumer(params, this.config);
    }

    kyc_update_consumer(params) {
      return new KycUpdateConsumer(params, this.config);
    }

    kyc_create_transaction(params) {
      return new KycCreateTransaction(params, this.config);
    }

    kyc_update_transaction(params) {
      return new KycUpdateTransaction(params, this.config);
    }

    kyc_upload_document(params) {
      return new KycUploadDocument(params, this.config);
    }

    kyc_download_document(params) {
      return new KycDownloadDocument(params, this.config);
    }

    kyc_make_call(params) {
      return new KycMakeCall(params, this.config);
    }

    kyc_update_call(params) {
      return new KycUpdateCall(params, this.config);
    }

    kyc_cpf(params) {
      return new KycCpf(params, this.config);
    }

    kyc_cnpj(params) {
      return new KycCnpj(params, this.config);
    }

    kyc_create_verification(params) {
      return new KycCreateVerification(params, this.config);
    }

    kyc_verification_status(params) {
      return new KycVerificationStatus(params, this.config);
    }

    kyc_verification_register(params) {
      return new KycVerificationRegister(params, this.config);
    }

    /*
      SCA
    */
    sca_checker(params) {
      return new ScaChecker(params, this.config);
    }

    /*
      Installments
    */
    installments_fetch(params) {
      return new InstallmentsFetch(params, this.config);
    }

    installments_show_details(params) {
      return new InstallmentsShowDetails(params, this.config);
    }

    /*
      Web Payment Form
    */
    wpf_create(params) {
      return new WpfCreate(params, this.config);
    }

    wpf_reconcile(params) {
      return new WpfReconcile(params, this.config);
    }

  };

  module.exports = Transaction;

}).call(this);
