// Generated by CoffeeScript 2.7.0
(function() {
  var JsonUtils, TravelData, _;

  _ = require('underscore');

  JsonUtils = require('../../utils/json_utils');

  TravelData = (function() {
    var legs, taxes;

    class TravelData {
      constructor(params) {
        this.params = params;
      }

      parseTravelData() {
        if (JsonUtils.isValidObjectChain(this.params, 'travel.legs')) {
          legs;
        }
        if (JsonUtils.isValidObjectChain(this.params, 'travel.taxes')) {
          return taxes;
        }
      }

    };

    legs = function() {
      return _.extend(this.params.travel, {
        legs: {
          leg: this.params.travel.legs
        }
      });
    };

    taxes = function() {
      return _.extend(this.params.travel, {
        taxes: {
          tax: this.params.travel.taxes
        }
      });
    };

    return TravelData;

  }).call(this);

  module.exports = TravelData;

}).call(this);
