// Generated by CoffeeScript 2.7.0
(function() {
  var KycCreateTransaction, Request;

  Request = require('../../../../request');

  /*
    Implement this to scrub a new transaction. We will take the information specific to that transaction and
    run various verification checks available, returning the recommendation, score, and third-party verification
    scrubbing results.
  */
  KycCreateTransaction = class KycCreateTransaction extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'json');
    }

    getTransactionType() {
      return 'kyc_create_transaction';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'kyc',
        path: 'api/v1/create_transaction'
      };
    }

    getTrxData() {
      return this.params;
    }

  };

  module.exports = KycCreateTransaction;

}).call(this);
