// Generated by CoffeeScript 2.7.0
(function() {
  var Domains;

  Domains = (function() {
    class Domains {};

    Domains.SUBDOMAINS = {
      "gate": {
        "production": "gate",
        "sandbox": "staging.gate"
      },
      "wpf": {
        "production": "wpf",
        "sandbox": "staging.wpf"
      },
      "smart_router": {
        "production": "prod.api",
        "sandbox": "staging.api"
      },
      "kyc": {
        "production": "kyc",
        "sandbox": "staging.kyc"
      }
    };

    return Domains;

  }).call(this);

  module.exports = Domains;

}).call(this);
