// Generated by CoffeeScript 2.7.0
(function() {
  var Environments;

  Environments = (function() {
    class Environments {};

    /*
       Live (Production) environment
    */
    Environments.PRODUCTION = 'production';

    /*
       Test (Staging) environment where no money are being transfered
    */
    Environments.STAGING = 'sandbox';

    return Environments;

  }).call(this);

  module.exports = Environments;

}).call(this);
