// Generated by CoffeeScript 2.7.0
(function() {
  var BaseConfiguration, _;

  _ = require('underscore');

  BaseConfiguration = class BaseConfiguration {
    constructor() {
      this.customer = {};
      this.gateway = {};
      this.notifications = {};
    }

    getConfigObject() {
      return this.mapConfigObject();
    }

    // Customer
    setCustomer(value) {
      return this.customer = value;
    }

    // Gateway
    setGateway(value) {
      return this.gateway = value;
    }

    // Notifications
    setNotifications(value) {
      return this.notifications = value;
    }

    mapConfigObject() {
      var configObject, ref, ref1, ref2;
      configObject = {};
      if ((ref = this.configuration) != null ? ref.customer : void 0) {
        this.setCustomer(this.configuration.customer);
        configObject.customer = this.customer;
      }
      if ((ref1 = this.configuration) != null ? ref1.gateway : void 0) {
        this.setGateway(this.configuration.gateway);
        configObject.gateway = this.gateway;
      }
      if ((ref2 = this.configuration) != null ? ref2.notifications : void 0) {
        this.setNotifications(this.configuration.notifications);
        configObject.notifications = this.notifications;
      }
      return configObject;
    }

  };

  module.exports = BaseConfiguration;

}).call(this);
