// Generated by CoffeeScript 2.7.0
(function() {
  var BaseConfiguration, FileConfiguration, _, config;

  _ = require('underscore');

  config = require('config');

  BaseConfiguration = require('./base_configuration');

  FileConfiguration = class FileConfiguration extends BaseConfiguration {
    constructor() {
      super();
      this.configuration = config;
    }

    static getType() {
      return 'file';
    }

  };

  module.exports = FileConfiguration;

}).call(this);
