// Generated by CoffeeScript 2.7.0
(function() {
  var Configuration, ManualConfiguration, _;

  _ = require('underscore');

  Configuration = require('./base_configuration');

  ManualConfiguration = class ManualConfiguration extends Configuration {
    constructor(configuration) {
      super();
      this.configuration = configuration;
    }

    static getType() {
      return 'manual';
    }

  };

  module.exports = ManualConfiguration;

}).call(this);
