// Generated by CoffeeScript 2.7.0
(function() {
  var Fashioncheque, FinancialBase, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Fashioncheque = class Fashioncheque extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.FASHIONCHEQUE;
    }

  };

  module.exports = Fashioncheque;

}).call(this);
