// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Intersolve, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Intersolve = class Intersolve extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.INTERSOLVE;
    }

  };

  module.exports = Intersolve;

}).call(this);
