// Generated by CoffeeScript 2.7.0
(function() {
  var FinancialBase, Tcs, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Tcs = class Tcs extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.TCS;
    }

  };

  module.exports = Tcs;

}).call(this);
