// Generated by CoffeeScript 2.7.0
(function() {
  var BitpayPayout, FinancialBase, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  BitpayPayout = class BitpayPayout extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.BITPAY_PAYOUT;
    }

  };

  module.exports = BitpayPayout;

}).call(this);
