// Generated by CoffeeScript 2.7.0
(function() {
  var BitpayRefund, FinancialBase, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  BitpayRefund = class BitpayRefund extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.BITPAY_REFUND;
    }

  };

  module.exports = BitpayRefund;

}).call(this);
