// Generated by CoffeeScript 2.7.0
(function() {
  var BitpaySale, FinancialBase, TransactionTypes;

  FinancialBase = require('../financial_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  BitpaySale = class BitpaySale extends FinancialBase {
    getTransactionType() {
      return TransactionTypes.BITPAY_SALE;
    }

  };

  module.exports = BitpaySale;

}).call(this);
