// Generated by CoffeeScript 2.7.0
(function() {
  var Cryptogram, Request, TransactionTypes;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  Cryptogram = (function() {
    class Cryptogram extends Request {
      getTransactionType() {
        return TransactionTypes.CRYPTOGRAM;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.CRYPTOGRAM_URL
        };
      }

      getTrxData() {
        return {
          'cryptogram_request': this.params
        };
      }

    };

    Cryptogram.prototype.CRYPTOGRAM_URL = 'v1/cryptogram';

    return Cryptogram;

  }).call(this);

  module.exports = Cryptogram;

}).call(this);
