// Generated by CoffeeScript 2.7.0
(function() {
  var DeleteToken, Request, TransactionTypes;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  DeleteToken = (function() {
    class DeleteToken extends Request {
      getTransactionType() {
        return TransactionTypes.DELETE_TOKEN;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.DELETE_TOKEN_URL
        };
      }

      getTrxData() {
        return {
          'delete_token_request': this.params
        };
      }

    };

    DeleteToken.prototype.DELETE_TOKEN_URL = 'v1/delete_token';

    return DeleteToken;

  }).call(this);

  module.exports = DeleteToken;

}).call(this);
