// Generated by CoffeeScript 2.7.0
(function() {
  var GetTokenizedCard, Request, TransactionTypes;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  GetTokenizedCard = (function() {
    class GetTokenizedCard extends Request {
      getTransactionType() {
        return TransactionTypes.GET_TOKENIZED_CARD;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.GET_CARD_URL
        };
      }

      getTrxData() {
        return {
          'get_card_request': this.params
        };
      }

    };

    GetTokenizedCard.prototype.GET_CARD_URL = 'v1/get_card';

    return GetTokenizedCard;

  }).call(this);

  module.exports = GetTokenizedCard;

}).call(this);
