// Generated by CoffeeScript 2.7.0
(function() {
  var Request, Tokenize, TransactionTypes;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  Tokenize = (function() {
    class Tokenize extends Request {
      getTransactionType() {
        return TransactionTypes.TOKENIZE;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.TOKENIZE_URL
        };
      }

      getTrxData() {
        return {
          'tokenize_request': this.params
        };
      }

    };

    Tokenize.prototype.TOKENIZE_URL = 'v1/tokenize';

    return Tokenize;

  }).call(this);

  module.exports = Tokenize;

}).call(this);
