// Generated by CoffeeScript 2.7.0
(function() {
  var Request, TransactionTypes, UpdateToken;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  UpdateToken = (function() {
    class UpdateToken extends Request {
      getTransactionType() {
        return TransactionTypes.UPDATE_TOKEN;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.UPDATE_TOKEN_URL
        };
      }

      getTrxData() {
        return {
          'update_token_request': this.params
        };
      }

    };

    UpdateToken.prototype.UPDATE_TOKEN_URL = 'v1/update_token';

    return UpdateToken;

  }).call(this);

  module.exports = UpdateToken;

}).call(this);
