// Generated by CoffeeScript 2.7.0
(function() {
  var Request, TransactionTypes, ValidateToken;

  Request = require('../../../request');

  TransactionTypes = require('../../../helpers/transaction/types');

  ValidateToken = (function() {
    class ValidateToken extends Request {
      getTransactionType() {
        return TransactionTypes.VALIDATE_TOKEN;
      }

      getUrl() {
        return {
          app: 'gate',
          path: this.VALIDATE_TOKEN_URL
        };
      }

      getTrxData() {
        return {
          'validate_token_request': this.params
        };
      }

    };

    ValidateToken.prototype.VALIDATE_TOKEN_URL = 'v1/validate_token';

    return ValidateToken;

  }).call(this);

  module.exports = ValidateToken;

}).call(this);
