// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, Country, FinancialBase, _;

  FinancialBase = require('../financial_base');

  _ = require('underscore');

  Country = require('../../../helpers/country');

  AlternativeBase = class AlternativeBase extends FinancialBase {
    constructor(params, configuration) {
      super(params, configuration);
    }

  };

  module.exports = AlternativeBase;

}).call(this);
