// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, FinancialBase, _;

  FinancialBase = require('../financial_base');

  _ = require('underscore');

  AlternativeBase = class AlternativeBase extends FinancialBase {};

  module.exports = AlternativeBase;

}).call(this);
