// Generated by CoffeeScript 2.5.1
(function() {
  var AlternativeBase, Country, FinancialBase, _;

  FinancialBase = require('../financial_base');

  _ = require('underscore');

  Country = require('../../../helpers/country');

  AlternativeBase = class AlternativeBase extends FinancialBase {
    constructor(params) {
      super(params);
      this.country = new Country();
      this.requiredFields = _.union(this.requiredFields, ['remote_ip', 'return_success_url', 'return_failure_url', 'customer_email', 'billing_address.country']);
      this.fieldsValues['billing_address.country'] = this.country.getCountries();
    }

  };

  module.exports = AlternativeBase;

}).call(this);
