// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, CashU, TransactionTypes;

  AlternativeBase = require('./alternative_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  CashU = class CashU extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.CASHU;
    }

    constructor(params) {
      super(params);
    }

  };

  module.exports = CashU;

}).call(this);
