// Generated by CoffeeScript 2.5.1
(function() {
  var AlternativeBase, P24, TransactionTypes;

  AlternativeBase = require('./alternative_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  P24 = class P24 extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.P24;
    }

    constructor(params) {
      super(params);
      this.fieldsValues['billing_address.country'] = ['AD', 'AT', 'BE', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'EL', 'ES', 'NL', 'IE', 'IS', 'LT', 'LV', 'LU', 'MT', 'DE', 'NO', 'PL', 'PT', 'SM', 'SK', 'SI', 'CH', 'SE', 'HU', 'GB', 'IT', 'US', 'CA', 'JP', 'UA', 'BY', 'RU'];
    }

  };

  module.exports = P24;

}).call(this);
