// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, PaypalExpress, TransactionTypes, _;

  AlternativeBase = require('./alternative_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  _ = require('underscore');

  PaypalExpress = class PaypalExpress extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.PAYPAL_EXPRESS;
    }

    constructor(params) {
      super(params);
      this.requiredFields = _.without(this.requiredFields, 'remote_ip', 'customer_email');
    }

  };

  module.exports = PaypalExpress;

}).call(this);
