// Generated by CoffeeScript 2.5.1
(function() {
  var AlternativeBase, Paysafecard, TransactionTypes;

  AlternativeBase = require('./alternative_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Paysafecard = class Paysafecard extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.PAYSAFECARD;
    }

    constructor(params) {
      super(params);
      this.fieldsValues['billing_address.country'] = ['AT', 'BE', 'CY', 'CZ', 'DK', 'FI', 'FR', 'DE', 'GR', 'IE', 'IT', 'LU', 'NL', 'NO', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE', 'CH', 'GB', 'HU', 'HR', 'MT', 'US', 'CA', 'MX', 'TR', 'AE'];
    }

  };

  module.exports = Paysafecard;

}).call(this);
