// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, Paysafecard, TransactionTypes;

  AlternativeBase = require('./alternative_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Paysafecard = class Paysafecard extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.PAYSAFECARD;
    }

    constructor(params, configuration) {
      super(params, configuration);
    }

  };

  module.exports = Paysafecard;

}).call(this);
