// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, Poli, TransactionTypes;

  AlternativeBase = require('./alternative_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Poli = class Poli extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.POLI;
    }

  };

  module.exports = Poli;

}).call(this);
