// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, PPRO, TransactionTypes;

  AlternativeBase = require('./alternative_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  PPRO = class PPRO extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.PPRO;
    }

  };

  module.exports = PPRO;

}).call(this);
