// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, Sofort, TransactionTypes;

  AlternativeBase = require('./alternative_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Sofort = class Sofort extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.SOFORT;
    }

    constructor(params) {
      super(params);
      this.fieldsValues['billing_address.country'] = ['AT', 'BE', 'DE', 'ES', 'FR', 'GB', 'IT', 'NL', 'CH', 'PL'];
    }

  };

  module.exports = Sofort;

}).call(this);
