// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, Sofort, TransactionTypes;

  AlternativeBase = require('./alternative_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  Sofort = class Sofort extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.SOFORT;
    }

  };

  module.exports = Sofort;

}).call(this);
