// Generated by CoffeeScript 2.7.0
(function() {
  var AlternativeBase, TransactionTypes, TransferToPayout;

  AlternativeBase = require('./alternative_base');

  TransactionTypes = require('../../../helpers/transaction/types');

  /*
    TransferTo Payout is an APM which provides 3 different payment services: BankAccount,
    MobileWallet and CashPickup
  */
  TransferToPayout = class TransferToPayout extends AlternativeBase {
    getTransactionType() {
      return TransactionTypes.TRANSFER_TO_PAYOUT;
    }

  };

  module.exports = TransferToPayout;

}).call(this);
