// Generated by CoffeeScript 2.7.0
(function() {
  var KycVerificationRegister, Request;

  Request = require('../../../../request');

  /*
    Verification register request can be performed by reference_id.
    A reference id registration allows you to store the reference id in Genesis
    and receive notifications in Genesis for it.
  */
  KycVerificationRegister = class KycVerificationRegister extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'json');
    }

    getTransactionType() {
      return 'kyc_verification_register';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'kyc',
        path: 'api/v1/verifications/register'
      };
    }

    getTrxData() {
      return this.params;
    }

  };

  module.exports = KycVerificationRegister;

}).call(this);
