// Generated by CoffeeScript 2.7.0
(function() {
  var KycVerificationRemoteIdentity, Request;

  Request = require('../../../../request');

  /*
    Used to verify documents provided by the customer.
  */
  KycVerificationRemoteIdentity = class KycVerificationRemoteIdentity extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'json');
    }

    getTransactionType() {
      return 'kyc_verification_remote_identity';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'kyc',
        path: 'api/v1/verifications'
      };
    }

    getTrxData() {
      return this.params;
    }

  };

  module.exports = KycVerificationRemoteIdentity;

}).call(this);
