// Generated by CoffeeScript 2.7.0
(function() {
  var KycVerificationStatus, Request;

  Request = require('../../../../request');

  /*
    Verification status check request can be performed by reference_id.
    A status check may be needed if async notification has not arrived yet or
    when kyc notifications are not used in general.
  */
  KycVerificationStatus = class KycVerificationStatus extends Request {
    constructor(params, configuration) {
      super(params, configuration, 'json');
    }

    getTransactionType() {
      return 'kyc_verification_status';
    }

    getData() {
      return this.params;
    }

    getUrl() {
      return {
        app: 'kyc',
        path: 'api/v1/verifications/status'
      };
    }

    getTrxData() {
      return this.params;
    }

  };

  module.exports = KycVerificationStatus;

}).call(this);
