// Generated by CoffeeScript 2.7.0
(function() {

  /*
    Check the status of a specific Brazilian personal's CPF number.
    The CPF number is provided in the request URL as a parameter.
  */
  var KycCpf, Request, util;

  Request = require('../../../../request');

  util = require('util');

  KycCpf = (function() {
    var CPF;

    class KycCpf extends Request {
      constructor(params, configuration) {
        super(params, configuration, 'json');
        this.populateIdentifier();
      }

      getTransactionType() {
        return 'kyc_cpf';
      }

      getData() {
        return this.params;
      }

      getUrl() {
        return {
          app: 'kyc',
          path: util.format(CPF, this.documentId)
        };
      }

      getTrxData() {
        return this.params;
      }

      // Populate Document ID used in the endpoint
      populateIdentifier() {
        this.documentId = '';
        return this.documentId = this.params instanceof Object && this.params.hasOwnProperty('document_id') ? this.params.document_id : void 0;
      }

    };

    CPF = '/api/v1/cpf/%s';

    return KycCpf;

  }).call(this);

  module.exports = KycCpf;

}).call(this);
