// Generated by CoffeeScript 2.7.0
(function() {
  var AmountValidator, NumberValidator;

  NumberValidator = require('./number_validator');

  AmountValidator = class AmountValidator extends NumberValidator {
    constructor() {
      super();
      this.min = 0.01;
      this.max = 1000000000.00;
    }

  };

  module.exports = AmountValidator;

}).call(this);
