// Generated by CoffeeScript 2.5.1
(function() {

  /*
    Validate bic
  */
  var BicValidator, Validator, _;

  Validator = require('./validator');

  _ = require('underscore');

  BicValidator = (function() {
    class BicValidator extends Validator {
      isValid(value) {
        value = String(value); // make sure we have string
        this.messages = [];
        if (value.length < 8 || value.length > 11) {
          this.messages.push('Should be string between 8 and 11 characters');
        }
        if (value.match(this.NOT_CHARACTERS_IN_FIRST_SIX)) {
          this.messages.push('Should include only characters in the first 6 positions');
        }
        if (this.messages.length) {
          return false;
        }
        return true;
      }

      getMessage(field) {
        return `Field ${field} has invalid value. ${this.messages.join(' and ')}`;
      }

    };

    BicValidator.prototype.NOT_CHARACTERS_IN_FIRST_SIX = /^[^A-Z]{6}.*$/;

    return BicValidator;

  }).call(this);

  module.exports = BicValidator;

}).call(this);
