// Generated by CoffeeScript 2.5.1
(function() {

  /*
    Validate iban
  */
  var IbanValidator, Validator, _;

  Validator = require('./validator');

  _ = require('underscore');

  IbanValidator = (function() {
    class IbanValidator extends Validator {
      isValid(value) {
        value = String(value); // make sure we have string
        this.messages = [];
        if (value.length > 34) {
          this.messages.push('Should be string shorter or equal 34');
        }
        if (value.match(this.NOT_STARTS_WITH_TWO_LETTERS)) {
          this.messages.push('Should start with valid country code');
        }
        if (this.messages.length) {
          return false;
        }
        return true;
      }

      getMessage(field) {
        return `Field ${field} has invalid value. ${this.messages.join(' and ')}`;
      }

    };

    IbanValidator.prototype.NOT_STARTS_WITH_TWO_LETTERS = /^[^A-Z]{2}.*$/;

    return IbanValidator;

  }).call(this);

  module.exports = IbanValidator;

}).call(this);
