// Generated by CoffeeScript 2.7.0
(function() {
  var NumberValidator, Validator, _;

  Validator = require('./validator');

  _ = require('underscore');

  /*
    Validate if number is between given min and max numbers
  */
  NumberValidator = class NumberValidator extends Validator {
    constructor(min = 0, max = 0) {
      super();
      this.min = min;
      this.max = max;
    }

    isValid(value) {
      if (this.min && value < this.min) {
        return false;
      } else if (this.max && value > this.max) {
        return false;
      }
      return true;
    }

    getMessage(field) {
      var message_suffix;
      if (this.min && this.max === 0) {
        message_suffix = ` Should be greater then ${this.min}`;
      } else if (this.min === 0 && this.max) {
        message_suffix = ` Should be lower then ${this.max}`;
      } else {
        message_suffix = ` Should be between ${this.min} and ${this.max}`;
      }
      return `Field ${field} has invalid value.${message_suffix}`;
    }

  };

  module.exports = NumberValidator;

}).call(this);
