// Generated by CoffeeScript 2.5.1
(function() {
  var RegExpValidator, Validator;

  Validator = require('./validator');

  RegExpValidator = class RegExpValidator extends Validator {
    constructor(pattern, message, options = '') {
      super();
      this.pattern = pattern;
      this.message = message;
      this.options = options;
    }

    isValid(value) {
      return (new RegExp(this.pattern, this.options)).test(value);
    }

    getMessage(field) {
      return `Field ${field} has invalid value. Expected: ${this.message}`;
    }

  };

  module.exports = RegExpValidator;

}).call(this);
