// Generated by CoffeeScript 2.5.1
(function() {
  var StringValidator, Validator, _;

  Validator = require('./validator');

  _ = require('underscore');

  /*
    Validate if string length is between given min and max length
  */
  StringValidator = class StringValidator extends Validator {
    constructor(min = 0, max = 0) {
      super();
      this.min = min;
      this.max = max;
    }

    isValid(value) {
      if (this.min && value.length < this.min) {
        return false;
      } else if (this.max && value.length > this.max) {
        return false;
      }
      return true;
    }

    getMessage(field) {
      var message_suffix;
      if (this.min && this.max === 0) {
        message_suffix = `longer or equal ${this.min}`;
      } else if (this.min === 0 && this.max) {
        message_suffix = `shorter or equal ${this.max}`;
      } else {
        message_suffix = `between ${this.min} and ${this.max}`;
      }
      return `Field ${field} has invalid value. Should be string ${message_suffix} characters`;
    }

  };

  module.exports = StringValidator;

}).call(this);
