// Generated by CoffeeScript 2.7.0
(function() {
  /*
    Need this only to check for instanceof in validation method
  */
  var Validator;

  Validator = class Validator {};

  module.exports = Validator;

}).call(this);
